### ISSUE TITLE
ui.image() not working on windows

### ISSUE THREAD

**Issue by Hamza-Rafi** [zauberzeug/nicegui#1039]
### Description

Using windows 10 here and running this comes up with an error.

Code:
```py
ui.image('https://picsum.photos/id/377/640/360')
ui.run(port=3000)
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\pinterestTesting\nom.py", line 100, in <module>
    ui.image('https://picsum.photos/id/377/640/360')
  File "C:\Users\PC\Desktop\pinterestTesting\.venv\lib\site-packages\nicegui\elements\image.py", line 16, in __init__     
    super().__init__(tag='q-img', source=source)
  File "C:\Users\PC\Desktop\pinterestTesting\.venv\lib\site-packages\nicegui\elements\mixins\source_element.py", line 16, 
in __init__
    if Path(source).is_file():
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1439, in is_file
    return S_ISREG(self.stat().st_mode)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\picsum.photos\\id\\377\\640\\360'
(.venv)
```

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @Hamza-Rafi!

It must have been introduced in 1.2.18 with PR #1016. We tried to automatically distinguish a local file path from a URL. By checking if "https://picsum.photos/id/377/640/360" is a file that exists locally, Windows seems to throw an OSError.

It should be fixed with commit [bde46be](https://github.com/zauberzeug/nicegui/commit/bde46be867605209fe2ed3cf17dfed12a55537a9). Will be released with the upcoming version 1.2.21.
