### ISSUE TITLE
error when using ui.select to set the clearable prop

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1069]
### Description

```python
from nicegui import ui

ui.select(["a", "b"]).props("clearable")
```

when using ui.select to set the clearable prop, an error occurs in the Python backend when selecting an option on the interface and then clicking the clear icon.

```
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Programs\Python\Python311\Lib\site-packages\nicegui\events.py", line 283, in handle_event
    result = handler() if no_arguments else handler(arguments)
                                            ^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\nicegui\elements\mixins\value_element.py", line 31, in handle_change
    self.set_value(self._msg_to_value(msg))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\nicegui\elements\select.py", line 64, in _msg_to_value
    return self._values[msg['args']['value']]
                        ~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @CrystalWindSnake!
We haven't considered the clearable prop for `ui.select`. But luckily this was an easy fix.
