### ISSUE TITLE
how can I use the getElement method to get the correct component id in a custom Vue component?

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1186]
### Description

code defined in the custom Vue component.

my_cp.js
```js
export default {
    template: `<div>id:{{value}}</div>`,
    data() {

        const htmlTagId = window.getElement(this.eleId)

        return {
            value: htmlTagId,
        };
    },
    props: {
        eleId: String,
    },
};

```

my_cp.py
```python
from nicegui.element import Element
class MyCp(Element, component="my_cp.js"):
    def __init__(self, eleId: int) -> None:
        super().__init__()
        self._props["eleId"] = str(eleId)
```

main.py
```python
from nicegui import ui
from my_cp import MyCp

label = ui.label("")
MyCp(label.id)
```

browser console has error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'r4')
    at getElement ((索引):40:32)
    at Proxy.data (my_cp.js:5:34)
    at $o (vue.global.prod.js:1:33311)
    at cs (vue.global.prod.js:1:61348)
    at vue.global.prod.js:1:48236
    at vue.global.prod.js:1:48244
    at B (vue.global.prod.js:1:48263)
    at M (vue.global.prod.js:1:46487)
    at _ (vue.global.prod.js:1:43586)
    at N (vue.global.prod.js:1:44869)
```

```
    <script>
      function getElement(id) {
        const _id = id instanceof HTMLElement ? id.id : id;
        return window.app.$refs["r" + _id];
      }
    </script>
```

the label html tag id is 'c4'

Is there something I missed? How can i conveniently and correctly get the id?

**Comment by falkoschindler** [comment]
Hi @CrystalWindSnake,

From within a Vue component you can get the ID of the HTML element simply like this: `this.$el.id`.

You're right, while the ID of the NiceGUI element in Python is an integer like `4`, the HTML ID is a string like `"c4"`. This is because HTML IDs [must start with a letter](https://www.w3.org/TR/html401/types.html#type-name).

**Comment by CrystalWindSnake** [comment]
@falkoschindler 
If I want to get the DOM element of a component with a specific id in a custom component, do I have to concatenate strings myself?

my_cp.js
```
const cpDom= document.getElementById(`c${this.eleId}`)
```

**Comment by falkoschindler** [comment]
@CrystalWindSnake I think so, yes.

**Comment by CrystalWindSnake** [comment]
Okay, thanks for your prompt response.
