### ISSUE TITLE
Refreshable UI with parameters throws an error

### ISSUE THREAD

**Issue by alex-bezverkhniy** [zauberzeug/nicegui#1340]
### Description

When I use "Refreshable UI with parameters" it throws next error:
```
refreshable.refresh() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/alex/Workspace/python/menu/.venv/lib/python3.10/site-packages/nicegui/events.py", line 283, in handle_event
    result = handler() if no_arguments else handler(arguments)
  File "/home/alex/Workspace/python/nicegui-menu/test.py", line 13, in <lambda>
    ui.button('Refresh for Tokyo', on_click=lambda: clock_ui.refresh('Asia/Tokyo'))
TypeError: refreshable.refresh() takes 1 positional argument but 2 were given
```
I use an example from the documentation:
```python
import pytz
from datetime import datetime
from nicegui import ui

@ui.refreshable
def clock_ui(timezone: str):
    ui.label(f'Current time in {timezone}:')
    ui.label(datetime.now(tz=pytz.timezone(timezone)).strftime('%H:%M:%S'))

clock_ui('Europe/Berlin')
ui.button('Refresh', on_click=clock_ui.refresh)
ui.button('Refresh for New York', on_click=lambda: clock_ui.refresh('America/New_York'))
ui.button('Refresh for Tokyo', on_click=lambda: clock_ui.refresh('Asia/Tokyo'))

ui.run()
```
nicegui version `1.2.21`

For version `1.3.7` I don't see the error but it doesn't refresh the UI
I've tested it on:
- **os**: Linux Ubuntu - `22.04.2 LTS`
- **python**: - `3.10.6`
- **browser**: Firefox - `115.0.2 (64-bit)`

**Comment by falkoschindler** [comment]
I found and fixed the problem: The wrapped `refresh` function swallowed the first positional argument with the `instance` parameter:
```py
def refresh(instance=self.instance, *args: Any, **kwargs: Any) -> None:
```
The fix is rather simple:
```py
def refresh(*args: Any, _instance=self.instance, **kwargs: Any) -> None:
```
I also extended the corresponding test to cover more cases.

**Comment by alex-bezverkhniy** [comment]
Thank you @falkoschindler!
