### ISSUE TITLE
app.shutdown bug in native mode

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#1416]
### Description

is reload supposed to be always True in native mode if not something is making it become true which doesnt allow me to shut down the app.
```python
from nicegui import ui, app

async def logout():
    app.shutdown()

ui.button('destroy window', on_click=lambda: logout)

ui.run(native=True, reload=False)
```
```
Traceback (most recent call last):
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\background_tasks.py", line 55, in _handle_task_result
    task.result()
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\events.py", line 310, in wait_for_result
    await result
  File "c:\Users\jude\Desktop\Stuff\Coding\Personal Projects\Passguard\app\src\windows\main.py", line 255, in logout
    app.shutdown()
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\app.py", line 64, in shutdown
    raise Exception('calling shutdown() is not supported when auto-reload is enabled')
Exception: calling shutdown() is not supported when auto-reload is enabled
```

**Comment by rodja** [comment]
Shutdown for native mode will be fixed/improved in the next release (see https://github.com/zauberzeug/nicegui/pull/1403).

**Comment by falkoschindler** [comment]
By the way, you're not _calling_ `logout`.

**Comment by Smug246** [comment]
> By the way, you're not _calling_ `logout`.

mb i just tried to quickly recreate the example. in my actual script i call it

**Comment by falkoschindler** [comment]
@Smug246 Ok. But it's tricky to understand the problem you're facing if the code doesn't match the traceback. With `reload=False` you shouldn't see this exception. So what _is_ your problem? Is it related to #1322 and #1403?
