### ISSUE TITLE
Unable to run nicegui examples

### ISSUE THREAD

**Issue by hexfet13** [zauberzeug/nicegui#143]
Hi all,
this project seems to be very interesting and i decided to try it running some example..... but I'm unable to try because I got these errors:

>>> from nicegui import ui
>>> 
>>> ui.label('Hello, world!')
<nicegui.elements.label.Label object at 0x7f34f2098f70>
>>> ui.markdown('Have a look at the full <br/> [API reference](reference)!')
<nicegui.elements.markdown.Markdown object at 0x7f34f2165e80>
>>> 
>>> ui.run()
NiceGUI ready to go on http://0.0.0.0:8080
ERROR:    Traceback (most recent call last):
  File "/home/hexfet13/.local/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/hexfet13/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/hexfet13/.local/lib/python3.8/site-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/home/hexfet13/.local/lib/python3.8/site-packages/nicegui/nicegui.py", line 36, in startup
    create_favicon_routes()
  File "/home/hexfet13/.local/lib/python3.8/site-packages/nicegui/page.py", line 330, in create_favicon_routes
    if globals.config.favicon:
AttributeError: 'NoneType' object has no attribute 'favicon'

ERROR on: Traceback (most recent call last):
  File "/home/hexfet13/.local/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/hexfet13/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/hexfet13/.local/lib/python3.8/site-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/home/hexfet13/.local/lib/python3.8/site-packages/nicegui/nicegui.py", line 36, in startup
    create_favicon_routes()
  File "/home/hexfet13/.local/lib/python3.8/site-packages/nicegui/page.py", line 330, in create_favicon_routes
    if globals.config.favicon:
AttributeError: 'NoneType' object has no attribute 'favicon'

ERROR:    Application startup failed. Exiting.
ERROR on: Application startup failed. Exiting.

I tried to uninstall and reinstall faviconc manually and I saw pip throw an error about a missing executable "/usr/bin/pip3.8", so I made a link to ...../pip3 and to reinstalling favicon with this new symbolic link pip3.3 => pip3 , the installation was successful.
But i still see the error "AttributeError: 'NoneType' object has no attribute 'favicon'" running the nicegui example.

My system information:
python version: 3.8.10 
pip version: 22.3
ubuntu 20.04

Any help to fix this error? Thank you!

**Comment by falkoschindler** [comment]
It looks like you are running a NiceGUI app from an interactive Python shell. Instead you should put your code in a file like main.py and run it with something like `python3 main.py`. At least this is the recommended way of using NiceGUI.

But your approach should also work by disabling auto-reload: `ui.run(reload=False)`. Otherwise uvicorn will try to detect file changes and reload the UI for you. But since there is no file, this doesn't work. The error message could be more descriptive though.

**Comment by hexfet13** [comment]
I tried to put the code in main.py: it works! thank you for the support.
I will try all the nicegui features soon.

Thanks again
