### ISSUE TITLE
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'

### ISSUE THREAD

**Issue by tianqiqiu** [zauberzeug/nicegui#1467]
### Description

when update 1.3.11 run script report this:
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'

but script can use normal.

**Comment by rodja** [comment]
Does it also happen with a simple code example? Is it working again if you downgrade to 1.3.10?

**Comment by tianqiqiu** [comment]
use 1.3.10 do not report this message. use 1.3.11 run script which in example also report this message.  i reinstalled python and nicegui. use 1.3.11 also report this message.  but another pc not use nicegui in virtualenv ,do not report this message.

**Comment by rodja** [comment]
Strange. There are almost no changes [between 1.3.10 and 1.3.11](https://github.com/zauberzeug/nicegui/compare/v1.3.10...v1.3.11). Could you try using virtalenv on the other pc? And maybe try to create a new project with virtual env in a separate directory on the pc where the error appears.

**Comment by tianqiqiu** [comment]
reinstall python and nicegui in a new pc ,this pc not install python before,  create new virtualenv of nicegui, run  this example: https://github.com/zauberzeug/nicegui/tree/main/examples/modularization/ 
report RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close', 
run other examples , [menu_and_tabs] and [single_page_app], not report the message.
though report this message , the script function is normal.

**Comment by tianqiqiu** [comment]
Traceback (most recent call last):
  File "D:\prjall\venv\niceenv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\prjall\venv\niceenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\prjall\venv\niceenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\async_drivers\asgi.py", line 58, in __call__
    await self.engineio_server.handle_request(scope, receive, send)
  File "D:\prjall\venv\niceenv\Lib\site-packages\socketio\asyncio_server.py", line 398, in handle_request
    return await self.eio.handle_request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\asyncio_server.py", line 257, in handle_request
    r = await self._handle_connect(environ, transport,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\asyncio_server.py", line 430, in _handle_connect
    ret = await s.handle_get_request(environ)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\asyncio_socket.py", line 89, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\asyncio_socket.py", line 143, in _upgrade_websocket
    return await ws(environ)
           ^^^^^^^^^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\async_drivers\asgi.py", line 235, in __call__
    await self.handler(self)
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\asyncio_socket.py", line 253, in _websocket_handler
    await asyncio.wait_for(writer_task, timeout=None)
  File "D:\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\asyncio_socket.py", line 207, in writer
    await ws.close()
  File "D:\prjall\venv\niceenv\Lib\site-packages\engineio\async_drivers\asgi.py", line 238, in close
    await self.asgi_send({'type': 'websocket.close'})
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in sender
    await send(message)
  File "D:\prjall\venv\niceenv\Lib\site-packages\starlette\middleware\sessions.py", line 84, in send_wrapper
    await send(message)
  File "D:\prjall\venv\niceenv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 338, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'. 

above is the full message.

**Comment by tianqiqiu** [comment]
when the sctipt is start, open the broswer page, this message is report, do not any operation in web page.

**Comment by kj4tmp** [comment]
I am experiencing the same error. Can trigger on closing or refreshing a client window.

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__        
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__   
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 86, in __call__  
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 26, in __call__      
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__      
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 26, in __call__      
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 58, in __call__    
    await self.engineio_server.handle_request(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/socketio/asyncio_server.py", line 398, in handle_request 
    return await self.eio.handle_request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_server.py", line 257, in handle_request 
    r = await self._handle_connect(environ, transport,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_server.py", line 430, in _handle_connect    ret = await s.handle_get_request(environ)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 143, in _upgrade_websocket
    return await ws(environ)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 235, in __call__
    await self.handler(self)
  File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 253, in _websocket_handler
    await asyncio.wait_for(writer_task, timeout=None)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 207, in writer
    await ws.close()
  File "/usr/local/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 238, in close
    await self.asgi_send({'type': 'websocket.close'})
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 84, in send_wrapper
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 345, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
```
my requirements.txt:
```
asyncua
fastapi[all]
requests
nicegui
annotated
fastapi-utils
```

and the output of pip list:

```
# pip list 
Package            Version
------------------ -----------
aiofiles           23.2.1
aiohttp            3.8.5
aiosignal          1.3.1
aiosqlite          0.19.0
annotated          0.0.2
anyio              3.7.1
async-timeout      4.0.3
asyncua            1.0.3
attrs              23.1.0
bidict             0.22.1
certifi            2023.7.22
cffi               1.15.1
charset-normalizer 3.2.0
click              8.1.7
cryptography       41.0.3
dnspython          2.4.2
email-validator    2.0.0.post2
fastapi            0.99.1
fastapi-socketio   0.0.10
fastapi-utils      0.2.1
frozenlist         1.4.0
greenlet           2.0.2
h11                0.14.0
httpcore           0.17.3
httptools          0.6.0
httpx              0.24.1
idna               3.4
itsdangerous       2.1.2
Jinja2             3.1.2
markdown2          2.4.10
MarkupSafe         2.1.3
multidict          6.0.4
nicegui            1.3.11
orjson             3.9.5
pip                23.1.2
pscript            0.7.7
pycparser          2.21
pydantic           1.10.12
Pygments           2.16.1
python-dateutil    2.8.2
python-dotenv      1.0.0
python-engineio    4.6.0
python-multipart   0.0.6
python-socketio    5.8.0
pytz               2023.3
PyYAML             6.0.1
requests           2.31.0
setuptools         65.5.1
six                1.16.0
sniffio            1.3.0
sortedcontainers   2.4.0
SQLAlchemy         1.4.49
starlette          0.27.0
typing_extensions  4.7.1
ujson              5.8.0
urllib3            2.0.4
uvicorn            0.22.0
uvloop             0.17.0
vbuild             0.8.2
watchfiles         0.19.0
websockets         11.0.3
wheel              0.41.1
yarl               1.9.2
```


I see the same error if requirements.txt is changed to nicegui==1.3.10
I run in docker container:

```
FROM python:slim
WORKDIR /
#install python deps

COPY ["./requirements.txt", "/requirements.txt"]
WORKDIR /
RUN python3 -m pip install -r requirements.txt --progress-bar off

#copy other stuff
WORKDIR /
COPY ["./redacted/", "/redacted/"]

WORKDIR /

CMD python3 -u -m redacted.main
```

**Comment by tianqiqiu** [comment]
aiofiles                  23.2.1
aiohttp                   3.8.5
aiosignal                 1.3.1
altgraph                  0.17.3
annotated-types           0.5.0
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.1.0
bidict                    0.22.1
certifi                   2023.7.22
charset-normalizer        3.2.0
click                     8.1.7
colorama                  0.4.6
fastapi                   0.101.1
fastapi-socketio          0.0.10
frozenlist                1.4.0
greenlet                  2.0.2
h11                       0.14.0
httpcore                  0.17.3
httptools                 0.6.0
httpx                     0.24.1
idna                      3.4
itsdangerous              2.1.2
Jinja2                    3.1.2
markdown2                 2.4.10
MarkupSafe                2.1.3
multidict                 6.0.4
nicegui                   1.3.11
orjson                    3.9.5
pefile                    2023.2.7
pip                       23.2.1
pscript                   0.7.7
pydantic                  2.2.1
pydantic_core             2.6.1
Pygments                  2.16.1
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.7
PyMySQL                   1.1.0
python-dotenv             1.0.0
python-engineio           4.6.0
python-multipart          0.0.6
python-socketio           5.8.0
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
setuptools                68.0.0
sniffio                   1.3.0
SQLAlchemy                2.0.20
starlette                 0.27.0
typing_extensions         4.7.1
uvicorn                   0.22.0
vbuild                    0.8.2
watchfiles                0.19.0
websockets                11.0.3
wheel                     0.40.0
yarl                      1.9.2
 above is my installed packages

**Comment by tianqiqiu** [comment]
> I have the same issue with several of the simple examples. Also tried with nicegui==1.3.10, same error.

are you update any package today?

**Comment by tianqiqiu** [comment]
> I am experiencing the same error. Can trigger on closing or refreshing a client window.
> 
> ```
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
>     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__        
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__   
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 86, in __call__  
>     await self.app(scope, receive, send_wrapper)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 26, in __call__      
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__      
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 26, in __call__      
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__    raise exc
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__    await self.app(scope, receive, sender)
>   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
>     raise e
>   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 58, in __call__    
>     await self.engineio_server.handle_request(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/socketio/asyncio_server.py", line 398, in handle_request 
>     return await self.eio.handle_request(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_server.py", line 257, in handle_request 
>     r = await self._handle_connect(environ, transport,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_server.py", line 430, in _handle_connect    ret = await s.handle_get_request(environ)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
>     return await getattr(self, '_upgrade_' + transport)(environ)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 143, in _upgrade_websocket
>     return await ws(environ)
>            ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 235, in __call__
>     await self.handler(self)
>   File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 253, in _websocket_handler
>     await asyncio.wait_for(writer_task, timeout=None)
>   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
>     return await fut
>            ^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 207, in writer
>     await ws.close()
>   File "/usr/local/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 238, in close
>     await self.asgi_send({'type': 'websocket.close'})
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in sender
>     await send(message)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 84, in send_wrapper
>     await send(message)
>   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 345, in asgi_send
>     raise RuntimeError(msg % message_type)
> RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
> ```
> 
> my requirements.txt:
> 
> ```
> asyncua
> fastapi[all]
> requests
> nicegui
> annotated
> fastapi-utils
> ```
> 
> and the output of pip list:
> 
> ```
> # pip list 
> Package            Version
> ------------------ -----------
> aiofiles           23.2.1
> aiohttp            3.8.5
> aiosignal          1.3.1
> aiosqlite          0.19.0
> annotated          0.0.2
> anyio              3.7.1
> async-timeout      4.0.3
> asyncua            1.0.3
> attrs              23.1.0
> bidict             0.22.1
> certifi            2023.7.22
> cffi               1.15.1
> charset-normalizer 3.2.0
> click              8.1.7
> cryptography       41.0.3
> dnspython          2.4.2
> email-validator    2.0.0.post2
> fastapi            0.99.1
> fastapi-socketio   0.0.10
> fastapi-utils      0.2.1
> frozenlist         1.4.0
> greenlet           2.0.2
> h11                0.14.0
> httpcore           0.17.3
> httptools          0.6.0
> httpx              0.24.1
> idna               3.4
> itsdangerous       2.1.2
> Jinja2             3.1.2
> markdown2          2.4.10
> MarkupSafe         2.1.3
> multidict          6.0.4
> nicegui            1.3.11
> orjson             3.9.5
> pip                23.1.2
> pscript            0.7.7
> pycparser          2.21
> pydantic           1.10.12
> Pygments           2.16.1
> python-dateutil    2.8.2
> python-dotenv      1.0.0
> python-engineio    4.6.0
> python-multipart   0.0.6
> python-socketio    5.8.0
> pytz               2023.3
> PyYAML             6.0.1
> requests           2.31.0
> setuptools         65.5.1
> six                1.16.0
> sniffio            1.3.0
> sortedcontainers   2.4.0
> SQLAlchemy         1.4.49
> starlette          0.27.0
> typing_extensions  4.7.1
> ujson              5.8.0
> urllib3            2.0.4
> uvicorn            0.22.0
> uvloop             0.17.0
> vbuild             0.8.2
> watchfiles         0.19.0
> websockets         11.0.3
> wheel              0.41.1
> yarl               1.9.2
> ```
> 
> I see the same error if requirements.txt is changed to nicegui==1.3.10 I run in docker container:
> 
> ```
> FROM python:slim
> WORKDIR /
> #install python deps
> 
> COPY ["./requirements.txt", "/requirements.txt"]
> WORKDIR /
> RUN python3 -m pip install -r requirements.txt --progress-bar off
> 
> #copy other stuff
> WORKDIR /
> COPY ["./redacted/", "/redacted/"]
> 
> WORKDIR /
> 
> CMD python3 -u -m redacted.main
> ```
@kj4tmp 
are you update any package today?

**Comment by tianqiqiu** [comment]
@kaldonia 
are you update any package today?

**Comment by Guiltx** [comment]
I have the same problem on closing browser page. try different versions of python(3.7;3.12) and different versions of nicegui(1.3.10;1.3.11;1.2.24), still the same.

**Comment by yesight** [comment]
I encountered the same problem after deploying a new server with nicegui (v1.3.11) installed, and to confirm the problem, I purposely found a windows computer that had never had Python installed before and deployed it, just installing nicegui and the related libraries that were automatically installed, and just running the authentication code in the examples. The same error is reproduced later.

**Comment by yesight** [comment]
After checking nicegui related modules one by one, found that it is caused by python-engineio conflict, after downgrading the version of python-engineio to V4.5.1, there is no similar problem again.
python-engineio==4.6.0   ->  python-engineio==4.5.1

**Comment by tianqiqiu** [comment]
@yesight  thank you, update python-engineio==4.5.1, the error is not report.

**Comment by Suraj1089** [comment]
I am encountering the same error when using nicegui within a **virtualenv environment**. I believe this issue arises specifically when using virtualenv because the code runs smoothly when executed without a virtual environment.

**Comment by falkoschindler** [comment]
Awesome! Thanks for the valuable insight, @yesight!

Let's summarize:
- NiceGUI requires fastapi-socketio^0.0.10,
    which requires python-socketio>=4.6.0,
    which requires python-engineio>=4.3.0.
- Just two days ago python-engineio released version 4.6.0 which causes "RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'." after closing a browser tab. I can reproduce it.

We definitely resolve this issue. Therefore I'll reopen it.

I see two possibilities:
1. Adjust the project.toml to limit python-engineio to <4.6.0.
2. Remove fastapi-socketio and its dependencies altogether.

I have a strong tendency to option 2, because we only use the `SocketManager` wrapper class anyway and option 1 wouldn't be very future-proof.

**Comment by rodja** [comment]
How would removing fastapi-socketio solve the issue with latest python-engineio? We would still need python-socketio which will then pull latest python-engineio.

**Comment by falkoschindler** [comment]
Oh, you're right! I totally mixed that up. Sure, we still depend on fastapi-socketio. 🤦🏻‍♂️

**Comment by falkoschindler** [comment]
Good news! @miguelgrinberg just released python-engineio 4.6.1 which fixes exactly our problem:
https://github.com/miguelgrinberg/python-engineio/issues/327
https://github.com/miguelgrinberg/python-engineio/releases/tag/v4.6.1

How should we define our dependency? Everything but 4.6.0 is fine...

**Comment by falkoschindler** [comment]
I think we can simply close this issue. We don't explicitly define a python-engineio version, so it makes no sense to add this dependency now. And everyone who is installing NiceGUI in a new environment will automatically get python-engineio 4.6.1 or newer.

**Comment by kj4tmp** [comment]
this issue has resurfaced for me.

pip list
Package              Version
-------------------- ------------
aiofiles             23.2.1
aiosqlite            0.19.0
annotated            0.0.2
annotated-types      0.6.0
anyio                4.2.0
asyncua              1.0.6
bidict               0.22.1
certifi              2023.11.17
cffi                 1.16.0
charset-normalizer   3.3.2
click                8.1.7
cryptography         41.0.7
dnspython            2.4.2
email-validator      2.1.0.post1
fastapi              0.109.0
fastapi-socketio     0.0.10
h11                  0.14.0
httpcore             1.0.2
httptools            0.6.1
httpx                0.26.0
idna                 3.6
ifaddr               0.2.0
influxdb-client      1.39.0
itsdangerous         2.1.2
Jinja2               3.1.3
markdown-it-py       3.0.0
markdown2            2.4.10
MarkupSafe           2.1.3
mdurl                0.1.2
nicegui              1.4.9
orjson               3.9.10
pip                  23.2.1
pscript              0.7.7
pycparser            2.21
pydantic             2.5.3
pydantic_core        2.14.6
pydantic-extra-types 2.4.1
pydantic-settings    2.1.0
Pygments             2.17.2
pyOpenSSL            23.3.0
pyserial             3.5
pyserial-asyncio     0.6
python-dateutil      2.8.2
python-dotenv        1.0.0
python-engineio      4.8.2
python-multipart     0.0.6
python-socketio      5.11.0
pytz                 2023.3.post1
PyYAML               6.0.1
reactivex            4.0.4
requests             2.31.0
rich                 13.7.0
setuptools           65.5.1
simple-websocket     1.0.0
six                  1.16.0
sniffio              1.3.0
sortedcontainers     2.4.0
starlette            0.35.1
typing_extensions    4.9.0
ujson                5.9.0
urllib3              2.1.0
uvicorn              0.25.0
uvloop               0.19.0
vbuild               0.8.2
vsi-terhw-piplc-core 0.0.2
watchfiles           0.21.0
websockets           12.0
wheel                0.42.0
wsproto              1.2.0

**Comment by rodja** [comment]
@kj4tmp please try our just released 1.4.10 which fixes an incompatibility with the latest FastAPI version.
