### ISSUE TITLE
The page doesn't reload when I change the code

### ISSUE THREAD

**Issue by skossan** [zauberzeug/nicegui#1480]
### Description

I've installed using `pip install nicegui`.

I took the boilerplate code from the website with the label.
```
from nicegui import ui

ui.label('Hello NiceGUI!')

ui.run()
```

If I change the label text and save the code the website doesn't reload.

The terminal shows me this and the website doesn't update.

*WARNING:  WatchFiles detected changes in 'main.py'. Reloading...*
*NiceGUI ready to go on http://localhost:8080, http://172.20.192.1:8080, and http://192.168.1.97:8080*

**Comment by rodja** [comment]
That is very odd. Do you see the change if you hit reload in the browser? Are there any messages in the JS console?

**Comment by skossan** [comment]
> That is very odd. Do you see the change if you hit reload in the browser? Are there any messages in the JS console?

`CTRL + R` and `CTRL + F5` didn't work. However. I actually restarted my PC and it works now! 

Quite weird.. But that's great!

**Comment by ercanhocaninyeri** [comment]
The same thing started happening to me after updating NiceGUI to v1.4.0. The page does not refresh after I change the code. Besides, it does not update the screen even if I reopen my Python IDE and run the code again. This is very strange. 
Another thing I have just encountered: It does not update the screen when I run another code! It was working pretty well in my old version (I guess it was 1.2.20)

On top of those, I receive the following error a while after I select a file using the [local file picker](https://github.com/zauberzeug/nicegui/tree/main/examples/local_file_picker). Maybe it is related to #1841. But in my case I do not have `native=True`. I use either `ui.run()` or `ui.run(reload=True)`.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\erca\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\erca\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\erca\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\erca\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\erca\Anaconda3\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\erca\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\erca\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\erca\OneDrive\Skrivebord\nice_gui\gui_v3.0.py", line 49, in <module>
    from local_file_picker import local_file_picker
  File "C:\Users\erca\OneDrive\Skrivebord\nice_gui\local_file_picker.py", line 5, in <module>
    from nicegui import events, ui
  File "C:\Users\erca\Anaconda3\lib\site-packages\nicegui\__init__.py", line 1, in <module>
    from . import context, elements, run, ui
  File "C:\Users\erca\Anaconda3\lib\site-packages\nicegui\run.py", line 7, in <module>
    from . import core, helpers
  File "C:\Users\erca\Anaconda3\lib\site-packages\nicegui\core.py", line 6, in <module>
    from socketio import AsyncServer
  File "C:\Users\erca\Anaconda3\lib\site-packages\socketio\__init__.py", line 1, in <module>
    from .client import Client
  File "C:\Users\erca\Anaconda3\lib\site-packages\socketio\client.py", line 3, in <module>
    import engineio
  File "C:\Users\erca\Anaconda3\lib\site-packages\engineio\__init__.py", line 8, in <module>
    from .async_drivers.tornado import get_tornado_handler
  File "C:\Users\erca\Anaconda3\lib\site-packages\engineio\async_drivers\tornado.py", line 6, in <module>
    import tornado.web
  File "C:\Users\erca\Anaconda3\lib\site-packages\tornado\web.py", line 87, in <module>
    from tornado.httpserver import HTTPServer
  File "C:\Users\erca\Anaconda3\lib\site-packages\tornado\httpserver.py", line 32, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "C:\Users\erca\Anaconda3\lib\site-packages\tornado\http1connection.py", line 34, in <module>
    from tornado import iostream
  File "C:\Users\erca\Anaconda3\lib\site-packages\tornado\iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
  File "C:\Users\erca\Anaconda3\lib\site-packages\tornado\netutil.py", line 34, in <module>
    _client_ssl_defaults = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
  File "C:\Users\erca\Anaconda3\lib\ssl.py", line 750, in create_default_context
    context.load_default_certs(purpose)
  File "C:\Users\erca\Anaconda3\lib\ssl.py", line 574, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\Users\erca\Anaconda3\lib\ssl.py", line 558, in _load_windows_store_certs
    for cert, encoding, trust in enum_certificates(storename):
KeyboardInterrupt
```

**Comment by rodja** [comment]
@ercanhocaninyeri have you tried clearing the browser cache or accessing from an incognito tab?
