### ISSUE TITLE
JSON exception when attempting to retrieve `app.storage.user` value

### ISSUE THREAD

**Issue by essenciary** [zauberzeug/nicegui#1547]
### Description

I'm trying to implement a crude authentication system, where for every protected page I check a `app.storage.user` value that lets me know if the user is authenticated or not. However, from time to time I get a JSON decode error: 

```python
ERROR:nicegui:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/kavi-4HkM4Syh-py3.11/lib/python3.11/site-packages/nicegui/background_tasks.py", line 56, in _handle_task_result
    task.result()
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/kavi-4HkM4Syh-py3.11/lib/python3.11/site-packages/nicegui/page.py", line 93, in wait_for_result
    return await result
           ^^^^^^^^^^^^
  File "/Volumes/Storage/Dropbox/Projects/xpyriments/laibrarian/ui_nicegui.py", line 211, in index
    if not is_auth():
           ^^^^^^^^^
  File "/Volumes/Storage/Dropbox/Projects/xpyriments/laibrarian/ui_nicegui.py", line 31, in is_auth
    return bool(app.storage.user.get('loggedin', False))
                ^^^^^^^^^^^^^^^^
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/kavi-4HkM4Syh-py3.11/lib/python3.11/site-packages/nicegui/storage.py", line 116, in user
    self._users[session_id] = PersistentDict(globals.storage_path / f'storage_user_{session_id}.json')
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/kavi-4HkM4Syh-py3.11/lib/python3.11/site-packages/nicegui/storage.py", line 44, in __init__
    data = json.loads(filepath.read_text()) if filepath.exists() else {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The JSON file looks good as far as I can tell.

**Comment by rodja** [comment]
Does that happen with every browser (or by forcing a new session with incognito mode)?

**Comment by essenciary** [comment]
It happened during regular browsing, not incognito. I've only tested in one browser, might've been Safari or Chrome, not sure what I was using at the time. 

Also, it happened at the time of implementing the feature. I haven't seen the error recently. Let me try to see if I can get it to come up again.

**Comment by falkoschindler** [comment]
Ok, I'll close this issue for now. Please let us know if you encounter the problem again.
