### ISSUE TITLE
Markdown could not find style module github-dark

### ISSUE THREAD

**Issue by superlou** [zauberzeug/nicegui#1595]
### Description

I am trying to render markdown with the following script:

```
from nicegui import ui
ui.markdown("Hello, *world*!")
ui.run()
```

I receive the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pygments/styles/__init__.py", line 78, in get_style_by_name
    mod = __import__('pygments.styles.' + mod, None, None, [cls])
ModuleNotFoundError: No module named 'pygments.styles.github-dark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lsimons/workspace/nicesheet/test.py", line 2, in <module>
    ui.markdown("Hello, *world*!")
  File "/home/lsimons/.local/lib/python3.10/site-packages/nicegui/elements/markdown.py", line 28, in __init__
    HtmlFormatter(nobackground=True, style='github-dark').get_style_defs('.body--dark .codehilite')
  File "/usr/lib/python3/dist-packages/pygments/formatters/html.py", line 413, in __init__
    Formatter.__init__(self, **options)
  File "/usr/lib/python3/dist-packages/pygments/formatter.py", line 66, in __init__
    self.style = _lookup_style(options.get('style', 'default'))
  File "/usr/lib/python3/dist-packages/pygments/formatter.py", line 21, in _lookup_style
    return get_style_by_name(style)
  File "/usr/lib/python3/dist-packages/pygments/styles/__init__.py", line 80, in get_style_by_name
    raise ClassNotFound("Could not find style module %r" % mod +
pygments.util.ClassNotFound: Could not find style module 'github-dark'.
```

I am running Linux MInt 21.1, Python 3.10.12, and nicegui 1.3.11.

**Comment by clueple** [comment]
I had the same problem ( could not find style module 'github-dark') before.
Once I upgrade pygments (if not, try pip install pygments) to 2.15.1  it worked.

I figured that out because my old laptop could run my app (written in nicegui) while my new pc couldn't.
Then I noticed the pygments version on my old laptop was 2.15.1 while my new pc had pygments version 2.11.1.

**Comment by rodja** [comment]
Oh, if that also works for @superlou we should increase minimum supported version of pygments to 2.15.1...

**Comment by superlou** [comment]
Confirming that it worked after I updated pygments (though I am on 2.16.1).
