### ISSUE TITLE
Error when uploading a folder

### ISSUE THREAD

**Issue by marcin-koziol** [zauberzeug/nicegui#1648]
### Description

1. I'm trying to upload a folder with files by dragging it from a file manager to the upload widget
2. Expected behavior: I  can get files and relative paths from uploaded folder
3. An exception from NiceGUI:

```python
from nicegui import ui

ui.upload(multiple=True, on_upload=lambda e: ui.notify(f'Uploaded {e.name}')).classes('max-w-full')

ui.run()

```

```
Traceback (most recent call last):
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/nicegui/middlewares.py", line 10, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/nicegui/elements/upload.py", line 53, in upload_route
    for data in (await request.form()).values():
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/requests.py", line 268, in _get_form
    self._form = await multipart_parser.parse()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/formparsers.py", line 254, in parse
    async for chunk in self.stream:
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/requests.py", line 230, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/nicegui/middlewares.py", line 10, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/nicegui/elements/upload.py", line 53, in upload_route
    for data in (await request.form()).values():
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/requests.py", line 268, in _get_form
    self._form = await multipart_parser.parse()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/formparsers.py", line 254, in parse
    async for chunk in self.stream:
  File "/home/van/.pyenv/versions/avl-nicegui/lib/python3.11/site-packages/starlette/requests.py", line 230, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
```

**Comment by falkoschindler** [comment]
Interesting, @marcin-koziol! We probably never thought about uploading a _folder_. I'll looking into it, maybe it's an easy fix.

**Comment by falkoschindler** [comment]
I'm not sure if QUploader actually supports uploading folders.
But I also don't understand the exception. Somehow awaiting the form data does not work...
Does anyone have an idea? 🙂

**Comment by natankeddem** [comment]
I tried running the given example. Dragging and dropping multiple files and clicking the cloud produced all checkmarks and notifications. Dragging and dropping a folder and clicking the cloud gave me a red triangle and `!`. In either case no console errors. On Windows 10, NiceGUI 1.3.14.

Maybe a `pip freeze` might provide insight?

**Comment by marcin-koziol** [comment]
> I'm not sure if QUploader actually supports uploading folders. But I also don't understand the exception. Somehow awaiting the form data does not work... Does anyone have an idea? 🙂

According to this one, https://github.com/quasarframework/quasar/issues/7030 it can, but it should be handled on the backend side too (recently I've tested folder upload using react and it worked), I'll try to make a PR 


> I tried running the given example. Dragging and dropping multiple files and clicking the cloud produced all checkmarks and notifications. Dragging and dropping a folder and clicking the cloud gave me a red triangle and `!`. In either case no console errors. On Windows 10, NiceGUI 1.3.14.
> 
> Maybe a `pip freeze` might provide insight?
1.3.14

**Comment by falkoschindler** [comment]
@marcin-koziol Have you made any progress towards a pull request? We would be very interested in a solution to this problem. 🙂

**Comment by falkoschindler** [comment]
I tend to closing this issue, since QUploader doesn't really seem to support uploading folders. You can't even select folders via the file selection dialog. And JavaScript doesn't even know if selected files are within a folder or not, but simply sends a collection of files. So I don't see a way how to spot an attempt to upload a folder. It might get fixed in a future Quasar release though.

**Comment by marcin-koziol** [comment]
> I tend to closing this issue, since QUploader doesn't really seem to support uploading folders. You can't even select folders via the file selection dialog. And JavaScript doesn't even know if selected files are within a folder or not, but simply sends a collection of files. So I don't see a way how to spot an attempt to upload a folder. It might get fixed in a future Quasar release though.

You're right, I was mislead by some random answer on Quasar's github
