### ISSUE TITLE
CLI pattern `if __name__ == "__main__": main()` does not work

### ISSUE THREAD

**Issue by nazarewk** [zauberzeug/nicegui#181]
One of the patterns for running CLI programs is:

```python
from nicegui import ui

def main():
    ui.label('Hello NiceGUI!')
    ui.button('BUTTON', on_click=lambda: ui.notify('button was pressed'))
    ui.run(port=8082)

if __name__ == "__main__"
    main()
```

This does not work with `reload=True`, because the reloadable `__name__` is `__mp_main__` instead. Most likely related to #143 

So I made it work using second entry:

```python
from nicegui import ui

def main():
    ui.label('Hello NiceGUI!')
    ui.button('BUTTON', on_click=lambda: ui.notify('button was pressed'))
    ui.run(port=8082)

if __name__ in ("__main__", "__mp_main__"):
    main()
```

Any idea what causes this and/or whether it can be fixed in `nicegui` itself?

**Comment by falkoschindler** [comment]
When Uvicorn is reloading the app (which happens for the first time right after starting the script), it re-evaluates main.py while searching for the nicegui:app object. In contrast to the original process, this "reloader" process has `__name__` "__mp_main__" with "mp" indicating "multi-processing". The main guard (successfully...) prevents the new process from evaluating `main()`, running `ui.run` and initializing `globals.config`. This is not what you want in this case.

Technically I don't see an easy solution for supporting the default main guard `if __name__ == '__main__':` for auto-reloading NiceGUI apps. Sure, you can extend the guard with `__mp_main__`. The question is, what is you motivation for the guard in the first place - besides it being a common pattern?

If you want to avoid the code in `main()` being evaluated a second time when starting with `reload=True`, you can wrap it in a page function:

```python
from nicegui import ui

@ui.page('/')
def main_page():
    ui.label('Hello NiceGUI!')
    ui.button('BUTTON', on_click=lambda: ui.notify('button was pressed'))

ui.run(port=8082)
```

Personally I'm not sure if you really need a main guard. Ideally your main script is short and concise, so that it does not need to be imported from anywhere.

**Comment by nazarewk** [comment]
I want my main script to serve as a CLI primarily and be able to spin up a web gui as an option.

**Comment by falkoschindler** [comment]
I'll close this issue, since I don't see how we can avoid the conflict with the main guard. Using NiceGUI as a secondary mode in an otherwise headless CLI application *in combination* with `reload=True` seems to be a rather tricky setup. But if including `__mp_main__` in the main guard helps, I'd leave it this way.

**Comment by denravonska** [comment]
Is this supposed to work when you invoke your code as a module? I get the exact same error message when using a `__main__.py` consisting of only

```Python
from nicegui import ui

ui.run()
```

```
$ python -m apto
ERROR:    Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "env/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "env/lib/python3.10/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "env/lib/python3.10/site-packages/nicegui/nicegui.py", line 62, in handle_startup
    raise RuntimeError('\n\n'
RuntimeError: 

You must call ui.run() to start the server.
If ui.run() is behind a main guard
   if __name__ == "__main__":
remove the guard or replace it with
   if __name__ in {"__main__", "__mp_main__"}:
to allow for multiprocessing.

ERROR:    Application startup failed. Exiting.
```

**Comment by falkoschindler** [comment]
Hi @denravonska!
Can you, please, open a new discussion for this matter? And can you give a bit more information about your file and directory structure so that we can reproduce the issue? Thanks!

**Comment by denravonska** [comment]
@falkoschindler Done, https://github.com/zauberzeug/nicegui/issues/1111 :)

**Comment by JT-Turner-Darksky** [comment]
I am having a similar issue where I get the aforementioned message about how to call ui.run. I have it on a Digital Ocean droplet. However, when I change the guard to 
if __name__ in ("__main__", "__mp_main__"):
    main(), gunicorn keeps filling the port with random processes, not allowing the app to run. Killing them just replaces them with new PIDs. This might be a Gunicorn issue and not a nice gui issue (or maybe Gunicorn isn't supported, even with 1 worker), so sorry if this issue isn't in the right place. Thanks for the help.

**Comment by rodja** [comment]
@JT-Turner-Darksky a droplet is just a linux system. Does it work locally? what is in your `main()` function. Have you checked if something like 

```py
if __name__ in ("__main__", "__mp_main__"):
    print('that works')
```

is executing correctly?

**Comment by JT-Turner-Darksky** [comment]
Yes,. However, something to note: "that works" appears twice before the app launches. I assume this is not expected behaviour. That might explain the reason the ports keep filling

**Comment by JT-Turner-Darksky** [comment]
Yes,. However, something to note: "that works" appears twice before the app launches. I assume this is not expected behaviour. That might explain the reason the ports keep filling

**Comment by JT-Turner-Darksky** [comment]
Sorry to bother, I figured it out. In addition to your help, it wasn't playing nice with gunicorn or uvicorn regardless of the number of workers. Y'all might want to put that somewhere because information about if gunicorn works with NiceGUI. Thanks for everything!
