### ISSUE TITLE
KeyError when removing a disconnected client

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#1826]
### Description

This bug shows as an exception on nicegui.io:

```
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]ERROR:nicegui:'b627df67-b6bb-4781-9b2e-a70233cc34f4'
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]Traceback (most recent call last):
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]  File "/app/nicegui/background_tasks.py", line 56, in _handle_task_result
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]    task.result()
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]  File "/app/nicegui/nicegui.py", line 174, in handle_disconnect
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]    delete_client(client.id)
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]  File "/app/nicegui/nicegui.py", line 241, in delete_client
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]    globals.clients.pop(client_id).remove_all_elements()
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T07:04:00Z app[3d8dd11b222908] fra [info]KeyError: 'b627df67-b6bb-4781-9b2e-a70233cc34f4'
```

In `on_disconnect` there is a check if the client is in `globals.clients`. But before actually popping it, we sleep for `delay` seconds in `handle_disconnect`. Afterwards the client is missing. This is probably due to `prune_clients` running in the background.

How to fix that? Should `prune_clients` be more conservative? Do we need it at all?

**Comment by falkoschindler** [comment]
Oh wait, `prune_clients` does not remove disconnected clients, but only those which never connected (i.e. have no `environ` set). Therefore this doesn't explain the exception.

What we can do anyway:

- Catch exceptions when deleting clients to avoid the "prune clients" loop to crash.
- Pass the whole client object to `delete_client` so that it doesn't have to find it in the dictionary.

But it would be even better to find the root cause.

**Comment by falkoschindler** [comment]
@rodja I have set the milestone to 1.4.1 since I think the root cause is still there and we should re-open this ticket.

**Comment by rodja** [comment]
Ok. https://github.com/zauberzeug/nicegui/pull/1838 just improves error handling and logging. We still need to investigate this further down the road.

**Comment by falkoschindler** [comment]
@rodja Do you see "Error while pruning slot stacks" in the logs, or is the error gone in 1.4?

**Comment by rodja** [comment]
Wonderful. The error seems to be fixed with 1.4. No error messages about pruning slot stacks appear.

**Comment by meslahik** [comment]
Today I upgrade NiceGUI v1.3.15 to v1.4.9
I have seen following error, kind of randomly, a couple of times while traversing pages or using UI elements:

```
[2024-01-09 16:47:41,129] {app.py:handle_exception:118} ERROR - '5006af06-b281-4ecf-9bc9-d73977aee6bf'
Traceback (most recent call last):
  File "C:\Gitrepos\charger-gate-vm\venv\Lib\site-packages\nicegui\background_tasks.py", line 52, in _handle_task_result
    task.result()
  File "C:\Gitrepos\charger-gate-vm\venv\Lib\site-packages\nicegui\client.py", line 257, in handle_disconnect
    self.delete()
  File "C:\Gitrepos\charger-gate-vm\venv\Lib\site-packages\nicegui\client.py", line 316, in delete
    del Client.instances[self.id]
        ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: '5006af06-b281-4ecf-9bc9-d73977aee6bf'
[2024-01-09 16:47:41,131] {main.py:on_exception:102} ERROR - '5006af06-b281-4ecf-9bc9-d73977aee6bf'
```

Any idea about the cause?

**Comment by falkoschindler** [comment]
Hi @meslahik, this is strange. Does it take very long to create the page, so that the client is pruned before even connected?
Does anybody else experience this problem?

**Comment by meslahik** [comment]
Not really, there are not a lot of elements or data load in each page.
I noticed the chance for this to happen when the application starts is higher (first time the initial page loads).

Sorry for being vague, it is happening time to time and have no clue about the cause.

**Comment by falkoschindler** [comment]
Ok, unfortunately we can't do much without more information about when it happens.
Maybe you can analyze it further and create a new issue with a code example that reproduces the key error. Thanks!

**Comment by malaval** [comment]
Hello, we are running Nicegui behind a Nginx reverse proxy (actually, Ingress Nginx Controller in a Kubernetes cluster).

We are having the error discussed in the thread. Example:

```
'ce5f5fef-b603-4922-b385-7ebc2bec0b9c'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.12/site-packages/nicegui/client.py", line 292, in delete_content
    self.delete()
  File "/usr/local/lib/python3.12/site-packages/nicegui/client.py", line 356, in delete
    del Client.instances[self.id]
        ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'ce5f5fef-b603-4922-b385-7ebc2bec0b9c'
```

We can see in the Nginx access logs websocket connections for the UUID impacted and these connection last sometimes more than 20-30 minutes, so I don't think they are terminated abruptly by Nginx. Nevertheless, we don't see any impact on the application... but these errors are noisy in the application logs.

In `client.py`, shouldn't we do (I can create the PR but wanted to ask first):

```
if self.id in Client.instances:
  del Client.instances[self.id]
```

instead of just:

```
del Client.instances[self.id]
```
