### ISSUE TITLE
"TypeError: object NoneType can't be used in 'await' expression" in every app

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#1843]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/1842

<div type='discussions-op-text'>

<sup>Originally posted by **zilch42** October 20, 2023</sup>
### Question

Hi, 

I'm getting the following error in the terminal on basically every app I try, even the most basic example:

```python
from nicegui import ui

ui.label('Hello NiceGUI!')

ui.run()
```
Just running this locally from vscode.

```
Task exception was never retrieved
future: <Task finished name='Task-24' coro=<AsyncServer._handle_event_internal() done, defined at C:\XXX\lib\site-packages\socketio\asyncio_server.py:513> exception=TypeError("object NoneType can't be used in 'await' expression")>
Traceback (most recent call last):
  File "C:\XXX\lib\site-packages\socketio\asyncio_server.py", line 515, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\XXX\lib\site-packages\socketio\asyncio_server.py", line 549, in _trigger_event
    ret = await handler(*args)
  File "C:\XXX\lib\site-packages\nicegui\nicegui.py", line 145, in on_handshake
    await sio.enter_room(sid, client.id)
TypeError: object NoneType can't be used in 'await' expression
```

It doesn't seem to actually represent any problems that I've found so far (i.e. the examples run fine, the app I'm building runs fine), but it does make the output logs difficult to read when I do get an actual error in my code, and I'm not sure if it means something that I should be concerned about or need to fix?</div>

**Comment by falkoschindler** [comment]
Even though we thought to have fixed this one in PR #1809, there is a wrong version number in commit
https://github.com/zauberzeug/nicegui/commit/e0f0d36595dfce0f74b45876a844a4e7747c50f3

I'll fix it today.
