### ISSUE TITLE
refreshable function in asynchronous task fails

### ISSUE THREAD

**Issue by miqsoft** [zauberzeug/nicegui#1857]
### Description

When trying to create an "component", that updates based on the result on an asynchronous web request I've got an strange error. I therefore created a minimal code example, also provided below, resulting in the error.

If there is a more clever way of achieving this update of a "component" based on an asynchronous task executed in the background, I'm lucky if any of you have an idea. 

Error:
```
future: <Task finished name='Task-19' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\async_server.py:595> exception=TypeError("on_handshake() missing 1 required positional argument: 'client_id'")>
Traceback (most recent call last):
  File "C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\async_server.py", line 597, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
TypeError: on_handshake() missing 1 required positional argument: 'client_id'
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<request_resource_from_server() done, defined at x:\nicegui examples\test.py:16> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "x:\nicegui examples\test.py", line 21, in request_resource_from_server
    refreshable_func(chosen_status)
  File "C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\functions\refreshable.py", line 69, in __call__
    target = RefreshableTarget(container=RefreshableContainer(), instance=self.instance, args=args, kwargs=kwargs)
  File "C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\element.py", line 68, in __init__
    self.client = _client or globals.get_client()
  File "C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\globals.py", line 105, in get_client
    return get_slot().parent.client
  File "C:\Users\kuelp\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\globals.py", line 101, in get_slot
    return get_slot_stack()[-1]
IndexError: list index out of range
```

Minimal example code:

``` python3
#!/usr/bin/env python3

from nicegui import ui
from nicegui.background_tasks import create
import asyncio
import random

status_list = ['unknown', 'published']

@ui.refreshable
def _show_status(status: str) -> None:
    if status == 'unknown':
        ui.icon('help', size='3em').classes('text-gray-500')
    elif status == 'published':
        ui.icon('check_box', size='3em').classes('text-green-500')

async def request_resource_from_server(refreshable_func):
    # simulate asynchronous server request
    await asyncio.sleep(2)
    # theoretically decide based upon request to the server (here random)
    chosen_status = random.choice(status_list)
    refreshable_func(chosen_status)

@ui.page('/')
def page(): 
    _show_status('unknown')
    create(request_resource_from_server(_show_status))


ui.run(port=1234)

```

**Comment by falkoschindler** [comment]
Hi @miqsoft, the background task tries to create a new UI container and is therefore looking for the right context. But since it runs independently of the client which requested the page, its slot stack (where NiceGUI usually holds the current context) is empty. We should show a better error message in this case...

But in your case you actually don't want to create a new container, but to reuse the existing one. Therefore you need to call `.refresh` on the refreshable function:
```py
refreshable_func.refresh('published')
```

Passing around seems a bit unconventional, but I understand that it can be useful from an architectural point of view. Alternatively you could simply write
```py
async def request_resource_from_server():
    await asyncio.sleep(2)
    _show_status.refresh('published')

@ui.page('/')
def page():
    _show_status('unknown')
    create(request_resource_from_server())
```
