### ISSUE TITLE
ui.upload() return error 

### ISSUE THREAD

**Issue by gitUser000** [zauberzeug/nicegui#193]
With the latest version (and latest docker container)

link : https://nicegui.io/reference#file_upload : don't show ui.notify "return" when selecting file and present "button"

Moreover with latest docker image : 
- testing for ui.upload give me this error

Task exception was never retrieved
future: <Task finished name='Task-150' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.11/site-packages/socketio/asyncio_server.py:522> exception=KeyError('lastModifiedDate')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/socketio/asyncio_server.py", line 562, in _trigger_event
    ret = handler(*args)
          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nicegui/nicegui.py", line 113, in handle_event
    sender.handle_event(msg)
  File "/usr/local/lib/python3.11/site-packages/nicegui/element.py", line 154, in handle_event
    result = listener.handler(msg)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nicegui/elements/upload.py", line 31, in upload
    files = [
            ^
  File "/usr/local/lib/python3.11/site-packages/nicegui/elements/upload.py", line 36, in <listcomp>
    lastModifiedDate=file['lastModifiedDate'],
                     ~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'lastModifiedDate'

**Comment by falkoschindler** [comment]
Thanks for reporting this issue!
We haven't been aware of [`lastModifiedDate`](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate) being deprecated, thus being undefined with some browsers. I removed it altogether from the event arguments.

**Comment by gitUser000** [comment]
👍 
Thanks for you job !

**Comment by falkoschindler** [comment]
It should be fixed in version 1.0.3, which has been released just now.
