### ISSUE TITLE
Access input element in javascript

### ISSUE THREAD

**Issue by sunnymax2002** [zauberzeug/nicegui#2185]
### Description

Hello

I'm trying to access the value in an input element using Javascript (I want to encrypt some data on the client browser before sending it to server), but below code doesn't show any content in the alert dialog, and I see error in terminal:

from nicegui import ui

async def basic_js():
    await ui.run_javascript(f'alert(getElement({pt.id}).value)')

pt = ui.input('Plain Text')
pt.props(add = f'for=c{pt.id}')

pwd = ui.input('Password', password=True, password_toggle_button=True)
ct = ui.label('Hello')
ui.button('Encrypt', on_click=basic_js)

ui.run()

The error in terminal:

JavaScript did not respond in time
Traceback (most recent call last):
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\background_tasks.py", line 55, in _handle_task_result
    task.result()
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\events.py", line 310, in wait_for_result
    await result
  File "D:\Code\git_repos\wiserbyday\source\gm_common\security\app.py", line 21, in basic_js
    await ui.run_javascript(f'alert(getElement({pt.id}).value)')
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\functions\javascript.py", line 27, in run_javascript
    return await client.run_javascript(code, respond=respond, timeout=timeout, check_interval=check_interval)
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\client.py", line 133, in run_javascript
    raise TimeoutError('JavaScript did not respond in time')
TimeoutError: JavaScript did not respond in time
Task exception was never retrieved
future: <Task finished name='Task-53' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\asyncio_server.py:522> exception=KeyError('result')>
Traceback (most recent call last):
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\asyncio_server.py", line 562, in _trigger_event
    ret = handler(*args)
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\nicegui.py", line 187, in on_javascript_response
    handle_javascript_response(client, msg)
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\nicegui.py", line 191, in handle_javascript_response
    client.waiting_javascript_commands[msg['request_id']] = msg['result']
KeyError: 'result'

**Comment by rodja** [comment]
`alert` does not return anything. So you should omit the `await`.
