### ISSUE TITLE
Updating NiceGUI broke existing project with "missing client_id" error 

### ISSUE THREAD

**Issue by PTruscott** [zauberzeug/nicegui#2274]
### Description

I updated my nicegui project requirements after last updating them around september.

This are the newly installed versions:

```
Successfully installed distro-1.9.0 fastapi-0.108.0 ifaddr-0.2.0 importlib-metadata-7.0.1 nicegui-1.4.8 openai-1.6.1 packaging-23.2 pyinstaller-6.3.0 python-engineio-4.8.1 python-socketio-5.10.0 pywebview-4.4.1 simple-websocket-
1.0.0 starlette-0.32.0.post1 typing-extensions-4.9.0 wsproto-1.2.0 zipp-3.17.0
```
After this, any running of a NiceGUI project errors immediately with the following error:

```
Task exception was never retrieved
future: <Task finished name='Task-255' coro=<AsyncServer._handle_event_internal() done, defined at C:\{project}\venv\lib\site-packages\socketio\async_server.py:595> exception=TypeError("_on_handshake() missing 1 required positional argument: 'client_id'")>
Traceback (most recent call last):
  File "C:\{project}\venv\lib\site-packages\socketio\async_server.py", line 597, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\{project}\venv\lib\site-packages\socketio\async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
TypeError: _on_handshake() missing 1 required positional argument: 'client_id'
```

This error always prints out 3 times, with only the `Task finished name` differing.  

The failed tasks:  Task-40, Task-103, Task-255

Even the following fails:

```py
from nicegui import ui

class Window:
    def __init__(self):
        self.number = 1

def run_gui():
    window = Window()
    ui.run()

run_gui()
```

**Comment by falkoschindler** [comment]
@PTruscott I guess you need to clear your browser's cache. The handshake API changed, so client and server need to speak the same language again.

**Comment by falkoschindler** [comment]
I assume the problem has been resolved. Let's close this issue.
