### ISSUE TITLE
Internal Server Error : Upgrade from 1.4.7 to 1.4.9

### ISSUE THREAD

**Issue by zak489** [zauberzeug/nicegui#2315]
### Description

Hi all,

I faced an issue when running the following code on a windows machine running Miniconda, with the latest version of the nicegui==1.4.9. The main issue is "Jinja2Templates.TemplateResponse() got an unexpected keyword argument 'request'" which has something to do with fastapi. May I know how one would solve this? The code below works for me under nicegui==1.4.7.

The code
```py
from nicegui import ui

ui.label("Hello NiceGUI!")

ui.run()
```

The errors
```
NiceGUI ready to go on http://localhost:8080, http://10.255.182.162:8080, http://169.254.155.134:8080, http://169.254.174.9:8080, and http://169.254.212.39:8080
Jinja2Templates.TemplateResponse() got an unexpected keyword argument 'request'
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\streams\memory.py", line 81, in receive
    return self.receive_nowait()
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\streams\memory.py", line 76, in receive_nowait       
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 78, in call_next       
    message = await recv_stream.receive()
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\streams\memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__     
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 108, in __call__       
    response = await self.dispatch_func(request, call_next)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\middlewares.py", line 10, in dispatch
    response = await call_next(request)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 84, in call_next       
    raise app_exc
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__        
    await responder(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__        
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__  
    raise exc
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__  
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\nicegui.py", line 54, in _get_index
    return Client.auto_index_client.build_response(request)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\client.py", line 122, in build_response
    return templates.TemplateResponse(
TypeError: Jinja2Templates.TemplateResponse() got an unexpected keyword argument 'request'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\streams\memory.py", line 81, in receive
    return self.receive_nowait()
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\streams\memory.py", line 76, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\streams\memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\middlewares.py", line 10, in dispatch
    response = await call_next(request)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\nicegui.py", line 54, in _get_index
    return Client.auto_index_client.build_response(request)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\client.py", line 122, in build_response
    return templates.TemplateResponse(
TypeError: Jinja2Templates.TemplateResponse() got an unexpected keyword argument 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\ProgramData\Miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\Miniconda3\lib\site-packages\starlette\middleware\errors.py", line 174, in __call__
    response = await self.handler(request, exc)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\nicegui.py", line 141, in _exception_handler_500
    return client.build_response(request, 500)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nicegui\client.py", line 122, in build_response
    return templates.TemplateResponse(
TypeError: Jinja2Templates.TemplateResponse() got an unexpected keyword argument 'request'
```

**Comment by rodja** [comment]
What Python version are you running? I came across the same error when running Python 3.8.0. The error is gone in 3.8.2 which I verified by running the specific Python versions in a docker container.

My reproduction was this bash line:

```bash
python3.8 -c "from starlette.templating import Jinja2Templates; Jinja2Templates('.')"
```

**Comment by rodja** [comment]
Please try updating FastAPI, there was a subtle change and maybe the Anaconda package deps of NiceGUI are perfect...

**Comment by zak489** [comment]
Hi Rodja, Thanks for the help. It is indeed the case here. I tried `conda update --all` and it only updates nicegui to 1.4.9, but keeps fastapi at 0.103.0. Only when I manually update the fastapi to 0.108.0 (latest version on January 2024), it works. Thanks a lot for the help!

**Comment by rodja** [comment]
Thanks for bringing this up. I just updated the conda dependencies. So ideally the next release will enforce that automatically.
