### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#2354]
### Description

just upgraded to the most recent version of nicegui and am running a basic script:
```
from nicegui import ui

ui.label('Hello World!')

ui.run(reload=True)
``` 
and this error is coming up but the site runs fine:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 103, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\engineio\async_drivers\asgi.py", line 69, in __call__
    await self.not_found(receive, send)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\engineio\async_drivers\asgi.py", line 117, in not_found
    await send({'type': 'http.response.start',
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 317, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.
ERROR:    closing handshake failed
Traceback (most recent call last):
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 959, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1161, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 730, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 248, in handler
    await self.close()
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1205, in write_frame
    await self.drain()
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1194, in drain
    await self.ensure_open()
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
```

**Comment by dreusel** [comment]
I encountered the same issue. This seems to be introduced by the release of fastapi 0.109.0 a few hours ago. (https://pypi.org/project/fastapi/#history). Fixing the fastapi version to 0.108.0 fixes the issue for me.

I would report an issue with fastapi since it seems that they broke something, but I know too little of what is going on to do so.

**Comment by rodja** [comment]
I boild it down to a FastAPI + fastapi-socketio example:

```py
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from fastapi_socketio import SocketManager

app = FastAPI()
socket_manager = SocketManager(app=app)
sio = socket_manager._sio


@sio.on('connect')
async def handle_join(sid, *args, **kwargs):
    await sio.emit('msg', 'Hello from FastAPI!')


@app.get("/", response_class=HTMLResponse)
async def get():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>SocketIO Test</title>
        <script src="https://cdn.socket.io/4.7.3/socket.io.min.js"></script>
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', (event) => {
                var socket = io("/", { path: "/ws/socket.io" });
                socket.on('msg', function(msg) {
                    document.body.innerHTML = '<h1>' + msg + '</h1>';
                });
            });
        </script>
    </head>
    <body>
        <h1>Connecting to SocketIO...</h1>
    </body>
    </html>
    """
```

It works fine with FastAPI 0.108.0 but on 0.109.0 the websocket route is not found.

**Comment by rodja** [comment]
And here further down to Starlette + socketio:

```py
import socketio
from starlette.applications import Starlette
from starlette.responses import HTMLResponse
from starlette.routing import Route

# Create a Socket.IO server
sio = socketio.AsyncServer(async_mode='asgi', cors_allowed_origins='*')
sio_app = socketio.ASGIApp(socketio_server=sio, socketio_path='socket.io')


async def homepage(_):
    return HTMLResponse("""
    <!DOCTYPE html>
    <html>
    <head>
        <title>SocketIO Test</title>
        <script src="https://cdn.socket.io/4.7.3/socket.io.min.js"></script>
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', (event) => {
                var socket = io("/", { path: "/ws/socket.io" });
                socket.on('msg', function(msg) {
                    document.body.innerHTML = '<h1>' + msg + '</h1>';
                });
            });
        </script>
    </head>
    <body>
        <h1>Connecting to SocketIO...</h1>
    </body>
    </html>
    """)


@sio.on('connect')
async def handle_connect(sid, *args, **kwargs):
    await sio.emit('msg', 'Hello from Starlette!')

app = Starlette(routes=[Route("/", homepage)])
app.mount('/ws', sio_app)
```

Works fine with Starlette [Version 0.32.0.post1](https://github.com/encode/starlette/releases/tag/0.32.0.post1) from November 23 but breaks with [Version 0.33.0](https://github.com/encode/starlette/releases/tag/0.33.0) from December 23.

**Comment by falkoschindler** [comment]
Should we fix FastAPI at 0.108.x? It's not the first time that a FastAPI release silently breaks NiceGUI. Maybe it's better to be more restrictive and to do explicit updates once in a while.

**Comment by rodja** [comment]
We should stick to Starlette 0.32.0.post1 for the next release if my just created question over at Starlette's repo does not yield any insights in the next few hours: https://github.com/encode/starlette/discussions/2413

**Comment by dreusel** [comment]
A clean install, after clearing pip caches etc, still gives the same errors. It does select the mentioned starlette version 0.35.1 but apparently by itself that does not solve it (I guess that's also what you meant with your comment over there @rodja ?)

**Comment by rodja** [comment]
@dreusel just installing newer Starlette version does not help. We needed to change our code. Which we did and just released with version [1.4.10](https://github.com/zauberzeug/nicegui/releases/tag/v1.4.10). This should fix the issue. Could you please give it a try?

**Comment by MuuXB** [comment]
I encountered the same issue (but I think the version I'm using has already addressed this problem).
The page refreshes normally, but after clicking the button, the following error occurs. @rodja @falkoschindler 

python=3.9.2
nicegui == 1.4.24
fastapi == 0.109.2

```
from ComstarApi import comstarlib
from nicegui import ui
from fastapi import FastAPI, Request, HTTPException
import uvicorn

server = FastAPI()

@ui.page("/")
def main():
    ui.label('Test')
    ui.button("start", on_click=lambda: ui.notify("hello"))

ui.run_with(
    server,
    mount_path='/',
    reconnect_timeout=1,
)
    

if __name__ == "__main__":
    uvicorn.run(server, host="127.0.0.1", port=8095)
```


```
INFO:     Started server process [3257]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8095 (Press CTRL+C to quit)
INFO:     ::ffff:10.60.163.0:0 - "GET / HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 487, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 103, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 487, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/nicegui/nicegui.py", line 44, in __call__
    return await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/engineio/async_drivers/asgi.py", line 77, in __call__
    await self.not_found(receive, send)
  File "/usr/local/lib/python3.9/dist-packages/engineio/async_drivers/asgi.py", line 125, in not_found
    await send({'type': 'http.response.start',
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 50, in sender
    await send(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 50, in sender
    await send(message)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 317, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.
INFO:     connection open
ERROR:    closing handshake failed
```
