### ISSUE TITLE
Binding update:modelValue event keeps reporting errors

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#2359]
### Description

```python
ele = ui.textarea()

def onModelValueChanged(e):
    print("test")

ele.on("update:modelValue", handler=onModelValueChanged)
```

The terminal keeps reporting errors
```
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
```

It doesn't seem to have anything to do with event binding. After I updated nicegui to the latest 1.4.9, the niecgui program doesn't start properly. Even after rolling back to a previous version it does the same thing

error message:
```
Traceback (most recent call last):
  File "D:\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 103, in __call__
    await self.app(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\engineio\async_drivers\asgi.py", line 69, in __call__
    await self.not_found(receive, send)
  File "D:\Programs\Python\Python311\Lib\site-packages\engineio\async_drivers\asgi.py", line 117, in not_found
    await send({'type': 'http.response.start',
  File "D:\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "D:\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 317, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.
ERROR:    closing handshake failed
Traceback (most recent call last):
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 959, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1161, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python311\Lib\asyncio\streams.py", line 726, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 248, in handler
    await self.close()
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1232, in write_close_frame        
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1205, in write_frame
    await self.drain()
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 1194, in drain
    await self.ensure_open()
  File "D:\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
```

**Comment by CrystalWindSnake** [comment]
After comparing, I found that it is a problem with fastapi version 0.109.0, back to 0.108.0 is not a problem.

**Comment by falkoschindler** [comment]
Thanks for the update, @CrystalWindSnake! That's what I suspected as well. I'll close this issue as duplicate.

**Comment by rodja** [comment]
Yes, this is the same underlying issue as in https://github.com/zauberzeug/nicegui/issues/2354 which we hopefully fixed with   https://github.com/zauberzeug/nicegui/pull/2360.
