### ISSUE TITLE
AuthMiddleware leads to startup error when no storage_secret is set

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#2438]
### Description

I use the example in https://github.com/zauberzeug/nicegui/blob/main/examples/authentication/main.py.
The `storage_secret` description says "secret key for browser-based storage (default: `None`, a value is required to enable ui.storage.individual and ui.storage.browser)". Since I don't use these storage types, I thought I could remove that parameter from `run()` call.
But then I get loads of exceptions on startup, all being similar to:

```
Traceback (most recent call last):
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\starlette\_utils.py", line 91, in collapse_excgroups
    raise exc
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\page_login.py", line 24, in dispatch
    if not app.storage.user.get('authenticated', False):
           ^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\nicegui\storage.py", line 131, in user
    if context.get_client().is_auto_index_client:
       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\nicegui\context.py", line 28, in get_client
    return get_slot().parent.client
           ^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\nicegui\context.py", line 20, in get_slot
    raise RuntimeError('The current slot cannot be determined because the slot stack for this task is empty.\n'
```

I think it either needs to be fixed or the description of `storage_secret` needs to be updated because it's not clear that this parameter is mandatory when using AuthMiddleware.
I can paste full output if you need.

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @me21!
The error message is indeed strange. We should check if it's a bug in the example or in the library itself.
