### ISSUE TITLE
Startup fails when using `if __name__ == "__main__":`

### ISSUE THREAD

**Issue by Quadrum1** [zauberzeug/nicegui#252]
The following code runs fine:
```python
from nicegui import ui
ui.label('some label')
ui.run()
```

However, the two following code-snippets do not run:
```python
from nicegui import ui
if __name__ == "__main__":
	ui.label('some label')
	ui.run()
```
```python
if __name__ == "__main__":
	from nicegui import ui
	ui.label('some label')
	ui.run()
```

In both cases, the raised error looks like the following.
```python
←[31mERROR←[0m:    Traceback (most recent call last):
  File "F:\Python\lib\site-packages\starlette\routing.py", line 671, in lifespan

    async with self.lifespan_context(app):
  File "F:\Python\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "F:\Python\lib\site-packages\starlette\routing.py", line 650, in startup
    handler()
  File "F:\Python\lib\site-packages\nicegui\nicegui.py", line 59, in handle_startup
    print(f'NiceGUI ready to go on http://{globals.host}:{globals.port}')
AttributeError: module 'nicegui.globals' has no attribute 'host'

←[31mERROR←[0m:    Application startup failed. Exiting.
Task raised an exception
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\nicegui\background_tasks.py", line 57, in _handle_task_result
    task.result()
  File "F:\Python\lib\site-packages\nicegui\binding.py", line 27, in loop
    await asyncio.sleep(globals.binding_refresh_interval)
AttributeError: module 'nicegui.globals' has no attribute 'binding_refresh_interval'
```

**Comment by Quadrum1** [comment]
Didn't spot that one, thanks for mentioning it!

**Comment by rodja** [comment]
I'll close this issue. If someone has an idea on how to improve the error message a pull request would be welcome.
