### ISSUE TITLE
example pyserial can not run

### ISSUE THREAD

**Issue by ProudRabbit** [zauberzeug/nicegui#2522]
### Description

When I run pyserial example, get some error.
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program_Files\Python\Python311\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program_Files\Python\Python311\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "D:\Program_Files\Python\Python311\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program_Files\Python\Python311\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "d:\Documents\2_Projects\Code\test_nicegui\test_pyserial.py", line 6, in <module>
    port = serial.Serial('COM14', baudrate=115200, parity=serial.PARITY_EVEN, rtscts=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\2_Projects\Code\test_nicegui\.venv\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "d:\Documents\2_Projects\Code\test_nicegui\.venv\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "d:\Documents\2_Projects\Code\test_nicegui\.venv\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM14': PermissionError(13, '拒绝访问。', None, 5)
```
then I annotated the code, only reserving `ui.run` but the error still occurs.
```python
import serial

from nicegui import app, run, ui

port = serial.Serial('COM14', baudrate=115200, parity=serial.PARITY_EVEN, rtscts=1)

ui.run()
```

if I delete `ui.run`, the error disappears and the serial can open.

**Comment by falkoschindler** [comment]
Hi @ProudRabbit, it looks like pyserial can't open the port "COM14".
Have you tried running the code without NiceGUI?

```py
import serial

port = serial.Serial('COM14', baudrate=115200, parity=serial.PARITY_EVEN, rtscts=1)
```

If it still fails, the problem is unrelated to NiceGUI and there's nothing we can do.

**Comment by ProudRabbit** [comment]
Hi @falkoschindler, thank you for your suggestion. I tried, and then the error disappeared.

**Comment by ProudRabbit** [comment]
I modified this example. Open the serial port after the UI startup is completed, now it is working properly.

```python
#!/usr/bin/env python
#-*- coding:utf-8 -*-

import serial
import asyncio
from nicegui import app, run, ui

port = serial.Serial()

def openSerialPort() -> None:
    port.port = "COM30"
    port.baudrate = 115200
    port.bytesize = serial.EIGHTBITS #number of bits per bytes
    port.parity = serial.PARITY_NONE #set parity check: no parity
    port.stopbits = serial.STOPBITS_ONE #number of stop bits
    port.timeout = 1            #non-block read
    port.xonxoff = False     #disable software flow control
    port.rtscts = False     #disable hardware (RTS/CTS) flow control
    port.dsrdtr = False       #disable hardware (DSR/DTR) flow control

    try:
        port.open()
    except:
        ui.notify("serial port not open")
        log.push("serial port not open")
    else:
        log.push("serial port open")
        ui.notify("serial port open")

ui.input('Send command').on('keydown.enter', lambda e: (
    port.write(f'{e.sender.value}\n'.encode()),
    e.sender.set_value(''),
))
log = ui.log()


async def read_loop() -> None:
    while not app.is_stopped:
        if port.is_open:
            line = await run.io_bound(port.readline)
            if line:
                log.push(line.decode())
        else:
            await asyncio.sleep(0.2)

app.on_startup(read_loop)

ui.button('Open Serial Port', on_click=openSerialPort)

ui.run()
```
