### ISSUE TITLE
bug:  _multiprocessing.SemLock( OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by xinetzone** [zauberzeug/nicegui#2785]
### Description

```
Error Type:
Runtime.ExitError

Error Message:
RequestId: 6de3378d-6967-4e8b-b0ef-41d851ca99e7 Error: Runtime exited with error: exit status 1

Logs:
time="2024-03-29T15:11:55Z" level=info msg="serving logs listener on sandbox.localdomain:1234" agent=logsApiAgent
TELEMETRY	Name: telemetry-extension	State: Already subscribed	Types: [Function]
Traceback (most recent call last):
File "/opt/python/bin/uvicorn", line 8, in 
sys.exit(main())
File "/opt/python/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/opt/python/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/opt/python/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/python/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/opt/python/uvicorn/main.py", line 409, in main
run(
File "/opt/python/uvicorn/main.py", line 575, in run
server.run()
File "/opt/python/uvicorn/server.py", line 65, in run
return asyncio.run(self.serve(sockets=sockets))
File "/var/lang/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
File "/opt/python/uvicorn/server.py", line 69, in serve
await self._serve(sockets)
File "/opt/python/uvicorn/server.py", line 76, in _serve
config.load()
File "/opt/python/uvicorn/config.py", line 433, in load
self.loaded_app = import_from_string(self.app)
File "/opt/python/uvicorn/importer.py", line 19, in import_from_string
module = importlib.import_module(module_str)
File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "/var/task/main.py", line 2, in 
from nicegui import app as gui, ui
File "/opt/python/nicegui/__init__.py", line 1, in 
from . import context, elements, run, ui
File "/opt/python/nicegui/run.py", line 9, in 
process_pool = ProcessPoolExecutor()
File "/var/lang/lib/python3.9/concurrent/futures/process.py", line 649, in __init__
self._call_queue = _SafeQueue(
File "/var/lang/lib/python3.9/concurrent/futures/process.py", line 168, in __init__
super().__init__(max_size, ctx=ctx)
File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 43, in __init__
self._rlock = ctx.Lock()
File "/var/lang/lib/python3.9/multiprocessing/context.py", line 68, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implemented
```

**Comment by falkoschindler** [comment]
Hi @xinetzone,

Can you, please, give a bit more context? What are you trying to do, what does your code look like?

ChatGPT says about your error message:

> The error message you're encountering, OSError: [Errno 38] Function not implemented, suggests that the environment in which you're running your application does not support multiprocessing in the way it's being used. This is a common issue when deploying Python applications on certain platforms that either restrict or do not fully support Python's multiprocessing capabilities, such as AWS Lambda, Google Cloud Functions, or other serverless environments.
>
> The ProcessPoolExecutor in the concurrent.futures module relies on the ability to fork processes, which is not available in all environments. The error arises from attempting to create a lock in a multiprocessing context, which is a necessary part of setting up a process pool. When the underlying system or environment does not implement or allow access to these process control mechanisms (like semaphores or shared memory), it results in the Function not implemented error.

So maybe you're running in an environment that doesn't fully support multiprocessing.

**Comment by xinetzone** [comment]
I use deta for deployment in [spacefile](https://deta.space/docs/en/build/reference/spacefile)

**Comment by rodja** [comment]
We have no experience with https://deta.space/. I'll update the title and transform it into a community question.
