### ISSUE TITLE
confilict with multiprocessing when running in native mode?

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#2962]
### Description
I'm using python 3.11.5  pywebview4.2.2 with my laptop, the native mode works fine in my desktop computer which uses python 3.11.4
```
niceGUI ready to go on http://localhost:8000
Process Process-1:
Traceback (most recent call last):
  File "D:\Program Files\python\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Program Files\python\Lib\multiprocessing\process.py", line 108, in run       
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\python\Lib\site-packages\nicegui\native\native_mode.py", line 45, in _open_window
    webview.settings.update(**core.app.native.settings)
    ^^^^^^^^^^^^^^^^
AttributeError: module 'webview' has no attribute 'settings'
```

**Comment by v479038280** [comment]
I create a virtual env ,and install pywebview5.1, it works fine,

**Comment by v479038280** [comment]
I create a virtual env ,and install pywebview5.1, it works fine,
