### ISSUE TITLE
[Pycharm Problem] Raise asyncio error when reload

### ISSUE THREAD

**Issue by atticus-lv** [zauberzeug/nicegui#3069]
### Description
sys: windows11
python: 3.11.7
nicegui: 1.4.25

video: https://github.com/zauberzeug/nicegui/assets/64118610/2b0f3835-f09f-468d-a58a-a8e2415bce86
error report
```
WARNING:  WatchFiles detected changes in 'load_test.py'. Reloading...
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\server.py", line 36, in run
    super().run(sockets=sockets)
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\atticus\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by atticus-lv** [comment]
seems to be a pycharm problem. Pure fastapi web will also cause this problem.
just go to run > edit config > find your config > turn on 'Emulate terminal in output console'
