### ISSUE TITLE
Cannot add file extensions to reload

### ISSUE THREAD

**Issue by Knochi** [zauberzeug/nicegui#31]
Hi,

i wanted to add ".yaml" files to the reload watcher.
``` python
ui.run(host='localhost', title='Test', uvicorn_reload_includes='.py,.yaml') 
```

But unfortunatly it fails with following traceback:
> Traceback (most recent call last):
>   File "c:/GIT/MySVGrenderer/SVGTest_svgwrite.py", line 2, in <module>
>     from nicegui import ui
>   File "C:\GIT\MySVGrenderer\.venv\lib\site-packages\nicegui\__init__.py", line 1, in <module>
>     from nicegui.nicegui import app, ui
>   File "C:\GIT\MySVGrenderer\.venv\lib\site-packages\nicegui\nicegui.py", line 4, in <module>
>     from .ui import Ui  # NOTE: before justpy
>   File "C:\GIT\MySVGrenderer\.venv\lib\site-packages\nicegui\ui.py", line 1, in <module>
>     class Ui:
>   File "C:\GIT\MySVGrenderer\.venv\lib\site-packages\nicegui\ui.py", line 2, in Ui
>     from .config import config  # NOTE: before run
>   File "C:\GIT\MySVGrenderer\.venv\lib\site-packages\nicegui\config.py", line 57, in <module>
>     config = Config(**args)
> TypeError: __init__() got an unexpected keyword argument 'uvicorn_reload_includes'
>

**Comment by Knochi** [comment]
upgrade from 0.7.21 to 0.7.26 fixed the issue
