### ISSUE TITLE
Native mode raises 'webview' has not attribute 'settings'

### ISSUE THREAD

**Issue by miek770** [zauberzeug/nicegui#3135]
### Description

I'm trying to run the following minimal example but it fails:

```python
from nicegui import ui

ui.label("Hi")

ui.run(native=True)
```

The error is (no window opened):

```
$ py main.py 
NiceGUI ready to go on http://localhost:8001
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run   
    self._target(*self._args, **self._kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\native\native_mode.py", line 45, in _open_window
    webview.settings.update(**core.app.native.settings)
    ^^^^^^^^^^^^^^^^
AttributeError: module 'webview' has no attribute 'settings'
```

I'm using:

- Python 3.11.4 64-bit
- nicegui 1.4.26
- pywebview 4.2.2

It used to work for me but I must have upgraded nicegui since then; I don't remember which version I was using.

---

Tried manually upgrading pywebview to version 5.1, which resolved the issue (the expected window appeared with no error).

**Comment by falkoschindler** [comment]
Hi @miek770,

Thanks for reporting this issue! It looks like the `settings` dictionary has only been introduced in pywebview 5.0. So we should bump its version in our pyproject.toml.
