### ISSUE TITLE
Show error message if WebGL is not supported

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#315]
https://nicegui.io/reference#3d_scene does not render the 3d scene. Neither do other examples.

**Comment by rodja** [comment]
Firefox works, but in Chrome I get the JS errors:

```
three.min.js:6 THREE.WebGLRenderer: Error creating WebGL context.
ws @ three.min.js:6
vue.global.prod.js:1 Error: Error creating WebGL context.
    at new ws (three.min.js:6:343972)
    at Proxy.mounted (scene:70:22)
    at vue.global.prod.js:1:29622
    at It (vue.global.prod.js:1:13973)
    at Bt (vue.global.prod.js:1:14051)
    at t.__weh.t.__weh (vue.global.prod.js:1:29501)
    at en (vue.global.prod.js:1:15275)
    at Z (vue.global.prod.js:1:53638)
    at mount (vue.global.prod.js:1:37859)
    at t.mount (vue.global.prod.js:1:120599)
(anonymous) @ vue.global.prod.js:1
```

**Comment by rodja** [comment]
Restarting Chrome has not helped. But enabling hardware acceleration in the Chrome settings did: https://github.com/mrdoob/three.js/issues/4927#issuecomment-181761464

Should we present a warning if three.js initialization fails?
