### ISSUE TITLE
Too short default time-out for notification element

### ISSUE THREAD

**Issue by denis-x** [zauberzeug/nicegui#3172]
### Description

Hello,

I am using notification element to display progress for preparing data and then for displaying it via PLOTLY.
An updating of plot by PLOTLY might take couple seconds for complex plot and during updating I am observing that Timer of Notification is attempting to delete notification, which has been already dismissed. It causes error messages like this:
Traceback (most recent call last):
  File "\venv\lib\site-packages\nicegui\elements\timer.py", line 96, in _invoke_callback
    await result
  File "\venv\lib\site-packages\nicegui\elements\notification.py", line 87, in try_delete
    if not await self.client.run_javascript(query)):
  File "\venv\lib\site-packages\nicegui\client.py", line 216, in send_and_wait
    return await JavaScriptRequest(request_id, timeout=timeout)
  File "\venv\lib\site-packages\nicegui\javascript_request.py", line 28, in __await__
    raise TimeoutError(f'JavaScript did not respond within {self.timeout:.1f} s') from e
TimeoutError: JavaScript did not respond within 1.0 s

From my side I am seeing 2 problem for being fixed:
1) "if not await self.client.run_javascript(query))" in notification.py is executed with default time-out 1s. which is not under control. I have fixed it on my side as "if not await self.client.run_javascript(query, timeout=(2 * timeout or getattr(self, 'timeout', 5.0))):" to be able to control it somehow via class attribute. You might have better solution than this.
2) Timer, that executes try_delete, is seemed continue to work after notification is dismissed (object not yet deleted). This timer is likely needed being stopped by dismiss.

BR Denis

**Comment by falkoschindler** [comment]
I'll close this issue as stale. Feel free to re-open it once you've got new information for us. Thanks!
