### ISSUE TITLE
nicegui-pack issure on windows: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by pierrejean-coudert** [zauberzeug/nicegui#3222]
### Description
OS: Windows 11
Python: 3.11.7

using `nicegui-pack` 1.4.26, launching the exe file shows:
```
nicegui-pack --onefile --name "main" main.py

main.exe

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\Temp\_MEI38522\nicegui\__init__.py", line 1, in <module>
    from . import elements, run, ui
  File "C:\Users\xxx\AppData\Local\Temp\_MEI38522\nicegui\run.py", line 7, in <module>
    from typing_extensions import ParamSpec
ModuleNotFoundError: No module named 'typing_extensions'
[43700] Failed to execute script 'main' due to unhandled exception!
```

**Comment by pierrejean-coudert** [comment]
solved by using pyInstaller 6.8.0 instead of a 5.x.y one
