### ISSUE TITLE
ui.clipboard.read does not work in Safari and native mode on Mac

### ISSUE THREAD

**Issue by TsaiTung-Chen** [zauberzeug/nicegui#3323]
### Description

Hi, I'm new to nicegui and considering moving from tkinter to this GUI framework. But I encountered some difficulties in the clipboard features. The following script from the [official website](https://nicegui.io/documentation/clipboard#client-side_clipboard) does not work well in both Safari browser and native mode, while in Microsoft Edge browser, it works as expected.

```python
from nicegui import ui

@ui.page('/')
async def index():
    ui.button('Write', on_click=lambda: ui.clipboard.write('Hi!'))

    async def read() -> None:
        ui.notify(await ui.clipboard.read())  # this does not work in Safari or native mode
    ui.button('Read', on_click=read)

ui.run()  # or `ui.run(native=True)`
```

The error message I got:
```python
JavaScript did not respond within 1.0 s
Traceback (most recent call last):
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/site-packages/nicegui/javascript_request.py", line 26, in __await__
    yield from asyncio.wait_for(self._event.wait(), self.timeout).__await__()
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/site-packages/nicegui/events.py", line 419, in wait_for_result
    await result
  File "/Users/tungchentsai/Downloads/nicegui_test/Clipboard/clipboard/main.py", line 8, in read
    ui.notify(await ui.clipboard.read())
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/site-packages/nicegui/functions/clipboard.py", line 7, in read
    return await run_javascript('navigator.clipboard.readText()')
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/site-packages/nicegui/client.py", line 222, in send_and_wait
    return await JavaScriptRequest(request_id, timeout=timeout)
  File "/Users/tungchentsai/miniforge3/envs/py39_nicegui/lib/python3.9/site-packages/nicegui/javascript_request.py", line 28, in __await__
    raise TimeoutError(f'JavaScript did not respond within {self.timeout:.1f} s') from e
TimeoutError: JavaScript did not respond within 1.0 s
```

My Mac:
M2 Pro Mac mini
macOS Sonoma 14.5

My package version:
nicegui: 1.4.28
pywebview: 5.1

**Comment by falkoschindler** [comment]
Hi @TsaiTung-Chen,

Unfortunately the browser might block the clipboard access for security reasons. As written in the [documentation](https://nicegui.io/documentation/clipboard):
> Note that your browser may ask for permission to access the clipboard or may not support this feature at all.

It might be better to access the clipboard within the JavaScript event handler directly on the client, as shown in the [second demo](https://nicegui.io/documentation/clipboard#client-side_clipboard).
