### ISSUE TITLE
ui.download doesn't work in native mode

### ISSUE THREAD

**Issue by paulGeoghegan** [zauberzeug/nicegui#3402]
### Description

I have been trying to use ui.download in order to download a file but it doesn't seem to work. It just prompts me to allow permission and then does nothing. It works in browser mode as you can see from the examples on the website but not in native mode.

**Comment by falkoschindler** [comment]
Hi @paulGeoghegan,

Can you, please, share the code for your `ui.download` element? It looks like some files are opened in your web browser and some in the native window itself.

And pywebview (which our native mode is based on) restricts downloads by default. Your can try setting
```py
app.native.settings['ALLOW_DOWNLOADS'] = True
```
But we're not sure if and when this flag is really necessary. See PR #2884 for a related discussion.

**Comment by paulGeoghegan** [comment]
@falkoschindler thanks for your reply. I will give this a try tomorrow and get back to you. I'm just using the same code as in the ui.upload example where the download functionality is demonstrated.

**Comment by paulGeoghegan** [comment]
@falkoschindler that fixed our issue. Without it we can't download any files but now we can. It might be worth mentioning this in the documentation.

**Comment by paulGeoghegan** [comment]
I was also wondering if you can pass an array of files to ui.download?

**Comment by falkoschindler** [comment]
> I was also wondering if you can pass an array of files to ui.download?

No, that's not possible at the moment. But you can simply call `ui.download` for each file individually.

**Comment by fercook** [comment]
This doesn't work on native mode for me, I am on a Mac M1, OS X 14.4.1, Python 3.11.
I can download ok in browser mode.

**Comment by falkoschindler** [comment]
@fercook What exactly does not work? What do expect to happen, and what happens instead?

**Comment by fercook** [comment]
I created this super simple and minimal test script:

```
from nicegui import ui, app

app.native.settings['ALLOW_DOWNLOADS'] = True

ui.button("Download", on_click=lambda: ui.download(b'Demo text','demo_file.txt'))

ui.run(native=True)
```

Clicking on the button creates a window that asks for a file name, and then produces a long error output:

```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/fercook/miniforge3/envs/ICHOIR/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/fercook/miniforge3/envs/nicegui/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/fercook/miniforge3/envs/nicegui/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/fercook/miniforge3/envs/nicegui/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/fercook/miniforge3/envs/nicegui/lib/python3.11/site-packages/webview/platforms/cocoa.py", line 283, in download_completionHandler_error_
    logger.error('Download error:', error)
Message: 'Download error:'
Arguments: (Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=blob:http://127.0.0.1:8001/843357a3-027a-4431-8c23-a030bd70a48c, NSErrorFailingURLKey=blob:http://127.0.0.1:8001/843357a3-027a-4431-8c23-a030bd70a48c, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <90903EBB-10EF-4E42-AC7A-74C8A97CD3CB>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <90903EBB-10EF-4E42-AC7A-74C8A97CD3CB>.<1>, NSUnderlyingError=0x60000110dec0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}},)
```

**Comment by rodja** [comment]
@fercook I can confirm the bug. Without native mode, downloading bytes works fine. But with native mode it raises this error. At least on OSX. Can anyone test on Windows/Linux?

**Comment by python-and-fiction** [comment]
Nicegui 1.4.34,
pywebview 5.1,
Windows 10 ltsc  build 19044.4412
No error in output.
```python3
from nicegui import ui, app

app.native.settings['ALLOW_DOWNLOADS'] = True

ui.button("Download", on_click=lambda: ui.download(b'Demo text','demo_file.txt'))

ui.run(native=True)
```
![image](https://github.com/user-attachments/assets/58c48c35-2295-40b1-887f-5fa9f360a32f)

**Comment by fercook** [comment]
Checked with Nicegui 1.4.34 and on OSX 14.4.1 it still gives the same error

**Comment by cleesmith** [comment]
In native mode using ui.download does work on my Windows 10 laptop:
```
from nicegui import ui, app
app.native.settings['ALLOW_DOWNLOADS'] = True
# ui.button("Download", on_click=lambda: ui.download(b'Demo text','demo_file.txt'))
ui.button("Download", on_click=lambda: ui.download(b'Demo text'))
ui.run(native=True)
```
... but fails on Macbook Pro OS 14.6 on Sep 3, 2024:
conda create -n whatever python=3.10  (miniconda)
Python: 3.10.14
pip: 24.0
NiceGUI: 2.0.1
FastAPI: 0.109.2
Uvicorn: 0.30.0
PyWebView: 5.1

**Comment by falkoschindler** [comment]
[pywebview 5.3](https://github.com/r0x0r/pywebview/releases/tag/5.3) just got released. But the problem seems to persist.
Can anyone reproduce it with a plain pywebview app? I'm struggling to do so.

**Comment by falkoschindler** [comment]
I can't reproduce the problem. I assume the problem has been fixed upstream.
