### ISSUE TITLE
Can't import socket_id

### ISSUE THREAD

**Issue by Sweetharry1992** [zauberzeug/nicegui#347]
Got this error when use `ui.scene()`:

> from ..globals import socket_id
ImportError: cannot import name 'socket_id' from partially initialized module 'nicegui.globals' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/nicegui/globals.py)

**Comment by falkoschindler** [comment]
@Sweetharry1992 Can you, please, provide more context, maybe even a short example that reproduces the problem? What version of NiceGUI are you using?

Using `ui.scene` alone does not raise any exception for me:

```py
from nicegui import ui

with ui.scene() as scene:
    scene.sphere()

ui.run()
```

**Comment by Sweetharry1992** [comment]
Traceback (most recent call last):
  File "/root/dotx/ui/click.py", line 1, in <module>
    from nicegui import ui
  File "/usr/local/lib/python3.10/dist-packages/nicegui/__init__.py", line 1, in <module>
    from . import elements, globals, ui
  File "/usr/local/lib/python3.10/dist-packages/nicegui/globals.py", line 8, in <module>
    from uvicorn import Server
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 26, in <module>
    from uvicorn.logging import TRACE_LOG_LEVEL
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/logging.py", line 7, in <module>
    import click
  File "/root/dotx/ui/click.py", line 1, in <module>
    from nicegui import ui
  File "/usr/local/lib/python3.10/dist-packages/nicegui/ui.py", line 38, in <module>
    from .elements.scene import Scene as scene
  File "/usr/local/lib/python3.10/dist-packages/nicegui/elements/scene.py", line 8, in <module>
    from ..globals import socket_id
ImportError: cannot import name 'socket_id' from partially initialized module 'nicegui.globals' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/nicegui/globals.py)

**Comment by Sweetharry1992** [comment]
Don't know what's happening here ... I run click me example successfully without getting error but now I gives same error when import nicegui

**Comment by falkoschindler** [comment]
Interesting! It looks like it depends on your file being named "click.py". [Uvicorn](https://pypi.org/project/uvicorn/) depends on [click](https://pypi.org/project/click/) which is mixed up with your click.py. Try a different name and it should work.

I wonder if this is a bug and/or if we can do anything about it.

**Comment by Sweetharry1992** [comment]
Thanks alot :)

**Comment by Sweetharry1992** [comment]
Fix my issue
