### ISSUE TITLE
Can't run nicegui in native mode after version 1.4.17 (plus solution)

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#3534]
### Description

Nicegui cannot be run in native mode after version 1.4.17. (or at least my app can't). The reason why is that the line:

webview.settings.update(**core.app.native.settings)

causes an error:

File "c:\users\gpott\AppData\local\programs\python\python311\Lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\native\native_mode.py", line 45, in _open_window
webview.settings.update(**core.app.native.settings)
^^^^^^^^^^^^^^^^
AttributeError: module 'webview' has no attribute 'settings'
Traceback (most recent call last):
File "F:\dropbox\newide2Copy1\newide2.py", line 14305, in
with ui.row().classes("w-full"):
^^^^^^^^
File "F:\dropbox\newide2Copy1\newide2.py", line 1039, in new_init
original_init(self, *args, **kwargs)
File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\elements\row.py", line 19, in init
super().init('div')
File "F:\dropbox\newide2Copy1\newide2.py", line 1039, in new_init
original_init(self, *args, **kwargs)
File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\element.py", line 76, in init
self.client = _client or context.client
^^^^^^^^^^^^^^
File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\context.py", line 47, in client
return self.slot.parent.client
^^^^^^^^^

I changed the line to:
for k,v in core.app.native.settings.items():
        webview.settings[k]=v
        
 as per the example in the documentation and everything appeared to work.  Not quite sure what is going on.  Webview definitely does have an attribute 'settings'.

**Comment by gavinpotter** [comment]
# webview.settings.update(**core.app.native.settings)
was inserted. webview.settings does not have an update method.  A quick solution was to replace this line with 
 for k,v in core.app.native.settings.items():
        webview.settings[k]=v

**Comment by gavinpotter** [comment]
sorry for the formatting - pressed enter not shift enter

**Comment by gavinpotter** [comment]
Error message:
This is the error message I receive when trying to run an app in native mode on 1.4.35
  File "c:\users\gpott\AppData\local\programs\python\python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\native\native_mode.py", line 45, in _open_window
    webview.settings.update(**core.app.native.settings)
    ^^^^^^^^^^^^^^^^
AttributeError: module 'webview' has no attribute 'settings'
Traceback (most recent call last):
  File "F:\dropbox\newide2Copy1\newide2.py", line 14305, in <module>
    with ui.row().classes("w-full"):
         ^^^^^^^^
  File "F:\dropbox\newide2Copy1\newide2.py", line 1039, in new_init
    original_init(self, *args, **kwargs)
  File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\elements\row.py", line 19, in __init__
    super().__init__('div')
  File "F:\dropbox\newide2Copy1\newide2.py", line 1039, in new_init
    original_init(self, *args, **kwargs)
  File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\element.py", line 76, in __init__
    self.client = _client or context.client
                             ^^^^^^^^^^^^^^
  File "C:\Users\gpott\python3112\Lib\site-packages\nicegui\context.py", line 47, in client
    return self.slot.parent.client
           ^^^^^^^^^

**Comment by python-and-fiction** [comment]
which version of pywebview do you use?

**Comment by python-and-fiction** [comment]
See it in
Native mode raises 'webview' has not attribute 'settings' · Issue #3135 · zauberzeug/nicegui
https://github.com/zauberzeug/nicegui/issues/3135
