### ISSUE TITLE
Failed when calling run_grid_method('updateGridOptions', {"pinnedTopRowData": ...})

### ISSUE THREAD

**Issue by guyingbo** [zauberzeug/nicegui#3538]
### Description

Here is the code when I use ui.aggrid:
```python
async def grid_filter(e):
    grid = e.sender
    filter_model = await grid.run_grid_method("getFilterModel")
    rows = do_something_with(filter_model)
    grid.run_grid_method('updateGridOptions', {"pinnedTopRowData": rows})
```
I got error in javascript console:
```javascript
Uncaught (in promise) ReferenceError: updateGridOptions is not defined
    at eval (eval at runMethod (nicegui.js:51:14), <anonymous>:1:1)
    at runMethod (nicegui.js:51:14)
    at Proxy.run_grid_method (aggrid.js:48:14)
    at runMethod (nicegui.js:57:32)
    at eval (eval at <anonymous> (nicegui.js:220:49), <anonymous>:1:21)
    at eval (eval at <anonymous> (nicegui.js:220:49), <anonymous>:1:102)
    at nicegui.js:220:49
```
I don't want to use 
```python
grid.options["pinnedTopRowData"] = rows
grid.update()
``` 
directly because it cause grid refresh which flush my filter input data.
I also tried `getGridOption` and `setGridOption`, they all throw the Uncaught error.

**Comment by falkoschindler** [comment]
Hi @guyingbo,

I think this is because NiceGUI comes with AG Grid 30.2.0, which has no `updateGridOptions`.
We will upgrade the AG Grid dependency in the upcoming 2.0.0 release.
See discussion #3182 for a similar problem.

**Comment by guyingbo** [comment]
I see. Thank you! @falkoschindler
