### ISSUE TITLE
Copy button on ui.code does not work

### ISSUE THREAD

**Issue by JeppeKlitgaard** [zauberzeug/nicegui#3564]
### Description

On `nicegui==1.4.35` pressing the copy button on a `ui.code(...)` block does not work and throws the following error in the browser console (tested on Brave and Edge on Windows):

```
TypeError: Cannot read properties of undefined (reading 'writeText')
    at eval (eval at <anonymous> (nicegui.js:174:17), <anonymous>:1:27)
    at vue.global.prod.js:6:62901
    at Lt (vue.global.prod.js:1:14656)
    at jt (vue.global.prod.js:1:14734)
    at jt (vue.global.prod.js:1:14835)
    at cn (vue.global.prod.js:1:16637)
    at x (quasar.umd.prod.js:6:34300)
    at k (quasar.umd.prod.js:6:43565)
    at Lt (vue.global.prod.js:1:14656)
    at jt (vue.global.prod.js:1:14734)
```

**Comment by falkoschindler** [comment]
Oh wow, thanks for reporting this issue, @JeppeKlitgaard!

It seems like the JavaScript API `navigator.clipboard` is not always available, only in secure contexts like HTTPS or localhost.

- [ ] Since there doesn't seem to be a workaround, we should hide the copy button in non-secure cases.
- [ ] Furthermore, we should fix `ui.clipboard` to warn the user and the developer about a non-existing clipboard API.

**Comment by JeppeKlitgaard** [comment]
Thank you for replying so quickly! I wish this worked over HTTP as that's what I am running for internal use, but I understand that this is simply a browser limitation
