### ISSUE TITLE
"Type is not JSON serializable: Tab" when binding value for tabs

### ISSUE THREAD

**Issue by hany** [zauberzeug/nicegui#3592]
### Description

I'm attempting to use `bind_value` on Tabs. Regardless if I bind the value to `ui.tabs` or `ui.tab_panels`, I get a `Type is not JSON serializable: Tab` error. The [documentation seems to suggest that this should work](https://nicegui.io/documentation/tabs#properties_for_ui_tabs):

```python
from nicegui import app, ui


@ui.page("/")
def index() -> None:
    with ui.tabs().bind_value(app.storage.user, "language") as tabs:
        one = ui.tab("Node.js")
        two = ui.tab("Python")
        three = ui.tab("Java")
        four = ui.tab("Go")
        five = ui.tab("Ruby")
        six = ui.tab("PHP")
    with ui.tab_panels(tabs, value=one) as tab_panels:
        with ui.tab_panel(one):
            ui.label("First tab")
        with ui.tab_panel(two):
            ui.label("Second tab")
        with ui.tab_panel(three):
            ui.label("Third tab")
        with ui.tab_panel(four):
            ui.label("Fourth tab")
        with ui.tab_panel(five):
            ui.label("Fifth tab")
        with ui.tab_panel(six):
            ui.label("Sixth tab")


ui.run(storage_secret="mysecretkey")
```

Error message:

```
Type is not JSON serializable: Tab
Traceback (most recent call last):
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/json/orjson_wrapper.py", line 59, in _orjson_converter
    raise TypeError(f'Object of type {obj.__class__.__name__} is not JSON serializable')
TypeError: Object of type Tab is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
    task.result()
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/storage.py", line 72, in backup
    await f.write(json.dumps(self, indent=self.indent))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: Tab
Type is not JSON serializable: Tab
Traceback (most recent call last):
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/json/orjson_wrapper.py", line 59, in _orjson_converter
    raise TypeError(f'Object of type {obj.__class__.__name__} is not JSON serializable')
TypeError: Object of type Tab is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
    task.result()
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/storage.py", line 72, in backup
    await f.write(json.dumps(self, indent=self.indent))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: Tab
Type is not JSON serializable: Tab
Traceback (most recent call last):
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/json/orjson_wrapper.py", line 59, in _orjson_converter
    raise TypeError(f'Object of type {obj.__class__.__name__} is not JSON serializable')
TypeError: Object of type Tab is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
    task.result()
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/storage.py", line 72, in backup
    await f.write(json.dumps(self, indent=self.indent))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hany/.pyenv/versions/nicegui/lib/python3.12/site-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: Tab
```

What's the proper to bind the value of the tab to a storage variable?

**Comment by falkoschindler** [comment]
Hi @hany,

This is a bit unfortunate, but binding the value of tabs or tab panels fails if it is set to the tab or panel object itself, not the name of it. Here is how it does work:
```py
with ui.tabs() as tabs:
    one = ui.tab("Node.js")
    two = ui.tab("Python")
    three = ui.tab("Java")
with ui.tab_panels(tabs, value=one._props["name"]).bind_value(app.storage.user, "language"):
    with ui.tab_panel(one):
        ui.label("First tab")
    with ui.tab_panel(two):
        ui.label("Second tab")
    with ui.tab_panel(three):
        ui.label("Third tab")
```
You can also replace `one._props["name"]` with the name `"Node.js"`. Unfortunately there is currently no `name` property to get the name without reaching into the private `_props` dictionary.

And I also had to move the binding down to the tab panels. Otherwise the tab value will be set via binding, but the tab panel value will be set programmatically to the fixed value of the first tab. And because both are bound together, the latter will overwrite what has been loaded from storage.

We should think about how to improve the usability or at least the documentation.

**Comment by hany** [comment]
Hey @falkoschindler thanks so much for this. It works now. Appreciate the quick reply.
