### ISSUE TITLE
Reload slow, no response to ctrl-C on Windows

### ISSUE THREAD

**Issue by superlou** [zauberzeug/nicegui#3652]
### Description

A simple application starts up in a second or two, but on making a change, reloading may take 10 seconds or more and may hang. Additionally, when hung, the terminal (both PowerShell and CMD) has no response to ctrl-c or clicking the close button. It's been about a year since I've used NiceGUI on Windows (I mostly use Linux) and I don't remember this behavior before. 

It sounds a bit like https://github.com/zauberzeug/nicegui/issues/3344, but this isn't in PyCharm. There are also some issues in uvicorn like https://github.com/encode/uvicorn/issues/1972 that sound related, but I know enough about the NiceGUI stack to know if that could be the root cause.

My test script is:

```py
from nicegui import ui

ui.button("Button 1")
ui.button("Button 2")
ui.button("Button 3")

ui.run()
```

Steps to recreate:

1. Make a simple NiceGUI script like the above named `simple.py`.
2. Run `python simple.py` in a Windows terminal.
3. Comment out one of the `ui.button(...)` calls and save the file.
4. Wait for "... Reloading..." to complete and show "NiceGUI ready to go..."

Environment:

* Windows 11 (also Windows 10, but mostly testing on Windows 11)
* Python 3.12.4 (x64)
* nicegui 1.4.37
* uvicorn 0.30.6
* fastapi 0.109.2

Edit: I tried the same test in WSL2 on the same computer and reloads are very fast, under a second.

**Comment by rodja** [comment]
Wow. That sounds serious. We aim for a super fast reload. Can anyone else with Windows reproduce this?

**Comment by python-and-fiction** [comment]
@superlou  do you test it in pure termial or in ide's integrated terminal? It soulds like similar bug in pycharm or in vscode i met.

**Comment by frankhuurman** [comment]
@superlou 
This might be a bit skewed because I'm using Windows 10 in a VM but for me with the nicegui version you specified and running your code example in cmd.exe it takes about 5 seconds on average to reload the page during file saves.
Using Git Bash takes about 4 seconds on average though it has trouble handling Ctrl + C for me as well.

On Linux it's nearly instant for me so seems to be a very Windows-y problem.

Upgrading to the latest NiceGUI version doesn't seem to change anything speed-wise either so it might be related to the way filewatcher picks up on filechanges on Windows in comparison to the other OS-es?

**Comment by superlou** [comment]
@frankhuurman, I don't think it's filewatcher, only because when I save, it immediately pops up with the notification that a file changed. The issues happen in the delay after.

Does nicegui use uvicorn logging? [This comment](https://github.com/encode/uvicorn/issues/1972#issuecomment-2351550842) describes my ctrl-c behavior.

**Comment by rodja** [comment]
Interesting @superlou! Uvicorn logging can be disabled with `ui.run(uvicorn_logging_level='critical')`.

**Comment by superlou** [comment]
Just got a chance to try it with logging disabled. No change unfortunately. Was really hoping it was something straightforward.

```
from nicegui import ui

ui.button("Button 1")
ui.button("Button 2")
ui.button("Button 3")

ui.run(uvicorn_logging_level='critical')
```

It's still 5 to 10 seconds to reload (if it does) when commenting and uncommenting buttons. I'm pretty sure it's reacting to `uvicorn_logging_level`, since I don't get the "WARNING:  WatchFiles detected changes in 'main.py'. Reloading..." message with the logging level set to critical.

**Comment by frankhuurman** [comment]
Just noticed that you're using Python 3.12.
I opened a NiceGUI issue a while back that's related to the Python 3.12 and Windows combination that might be similar to your issue: https://github.com/zauberzeug/nicegui/issues/2138

Could you try your same code using Python 3.11 on Win 11?

Back then it seemed to be an upstream problem that needed to be fixed but I assumed that would've been done by now, but I'm curious if downgrading your Python version solves the issue for now.

**Comment by superlou** [comment]
I used uv to test with Python 3.11.9, and it's the same behavior. WatchFiles detects changes immediately, but it takes about 15 seconds to respond in the browser.

**Comment by NebularNerd** [comment]
I'm just starting out with NiceGUI on Win11 running Python 3.10 and have had similar issues. Same as @superlou I'll start the server, make a change in VSCODE and it sometimes will reload ok, but it's 50/50 between that or just locking up and needing me to kill Python in the task manger.

Running it via Powershell in Microsoft Terminal if that helps.

**Comment by genotrance** [comment]
I'm seeing the same issue on Windows - reloads (and loads) are super slow and frustrating. 

Python 3.12.7
nicegui 2.5.0
fastapi 0.115.4
uvicorn 0.32.0

**Comment by superlou** [comment]
I'm not sure this is the root cause, but is there a way to try the solution suggested in https://github.com/encode/uvicorn/issues/1972#issuecomment-2420335831 to see if it's something related to filewatches in uvicorn? I'm not sure how to configure nicegui to test that.

**Comment by falkoschindler** [comment]
@superlou This works for me on Mac:
```py
watchfiles --filter python "python main.py"
```

**Comment by superlou** [comment]
Unfortunately, when I edit the test file (same process as earlier by commenting/un-commenting buttons) on Windows, either the page doesn't update or I get a permissions error:

```
PS C:\workspace\nicegui-test> watchfiles --filter python "python main.py"
[08:27:34] watchfiles v0.24.0 👀  path="C:\workspace\nicegui-test" target="python main.py" (command) filter=PythonFilter...
NiceGUI ready to go on http://localhost:8080, http://192.168.40.71:8080, and http://192.168.56.1:8080
[08:27:40] 1 change detected
NiceGUI ready to go on http://localhost:8080, http://192.168.40.71:8080, and http://192.168.56.1:8080
[08:27:48] 1 change detected
NiceGUI ready to go on http://localhost:8080, http://192.168.40.71:8080, and http://192.168.56.1:8080
[08:27:53] 1 change detected
NiceGUI ready to go on http://localhost:8080, http://192.168.40.71:8080, and http://192.168.56.1:8080
WARNING:  WatchFiles detected changes in 'main.py'. Reloading...
[08:28:05] 1 change detected
Traceback (most recent call last):
  File "C:\Users\lsimons\AppData\Local\Programs\Python\Python312\Lib\site-packages\watchfiles\run.py", line 149, in run_process
    process.stop(sigint_timeout=sigint_timeout, sigkill_timeout=sigkill_timeout)
  File "C:\Users\lsimons\AppData\Local\Programs\Python\Python312\Lib\site-packages\watchfiles\run.py", line 327, in stop
    os.kill(self.pid, signal.SIGINT)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lsimons\AppData\Local\Programs\Python\Python312\Scripts\watchfiles.exe\__main__.py", line 7, in <module>
  File "C:\Users\lsimons\AppData\Local\Programs\Python\Python312\Lib\site-packages\watchfiles\cli.py", line 171, in cli
    run_process(
  File "C:\Users\lsimons\AppData\Local\Programs\Python\Python312\Lib\site-packages\watchfiles\run.py", line 153, in run_process
    process.stop()
  File "C:\Users\lsimons\AppData\Local\Programs\Python\Python312\Lib\site-packages\watchfiles\run.py", line 327, in stop
    os.kill(self.pid, signal.SIGINT)
PermissionError: [WinError 5] Access is denied
```

**Comment by superlou** [comment]
The problem still generally persists with version 2.11, though with the very simple test example I've been doing, I just noticed that if I wait for the browser to autorefresh, it may take 5 to 30 seconds. If I right-click on the Windows Terminal with Powershell that I used to start the nicegui script, it updates a second or so after right-clicking. I'm not sure what that means, but it seems interesting.

**Comment by jdavidremm** [comment]
Same issue for me
W11
Vscode
Latest nicegui version
Python 3.11 3.12 and 3.13

Works only if i CTRL F5 the browser or if I kill and restart it

**Comment by collisee** [comment]
same issue here
Windows 11 24h2 using default terminal (powershell)
Python 3.11
Ctrl F5 doesn't seem to help, only kill then restart in Task manager work

**Comment by falkoschindler** [comment]
That's very unfortunate, @superlou, @jdavidremm and @collisee!
It would be great if anyone with a Windows system could reproduce the problem and dig deeper to find the underlying cause.

**Comment by Yuerchu** [comment]
I'm also using Windows 11, Python 3.12.2, and NiceGUI 2.9.0. On Windows, I have a project that even fails to use auto-reloading. When using the default log level of NiceGUI, it stops at the "WARNING: WatchFiles detected changes in 'main.py'. Reloading..." of WatchFile; when switching the log level to Debug, it stops at the "INFO: Finished server process [26852]" of Uvicorn. I encountered this issue when using NiceGUI 2.5.0 on Windows and it wasn't resolved until NiceGUI 2.11. Additionally, I have encountered other problems in the new versions of NiceGUI, and I will open a new issue to explain them.

**Comment by superlou** [comment]
> That's very unfortunate, [@superlou](https://github.com/superlou), [@jdavidremm](https://github.com/jdavidremm) and [@collisee](https://github.com/collisee)! It would be great if anyone with a Windows system could reproduce the problem and dig deeper to find the underlying cause.

If we're trying to determine if it's a uvicorn or nicegui root cause, do you know what would be a very simple example of how uvicorn is started/used by nicegui that I could test out? Something representative of how uvicorn is used, without overlapping nicegui?

**Comment by sht2017** [comment]
> > That's very unfortunate, [@superlou](https://github.com/superlou), [@jdavidremm](https://github.com/jdavidremm) and [@collisee](https://github.com/collisee)! It would be great if anyone with a Windows system could reproduce the problem and dig deeper to find the underlying cause.
> 
> If we're trying to determine if it's a uvicorn or nicegui root cause, do you know what would be a very simple example of how uvicorn is started/used by nicegui that I could test out? Something representative of how uvicorn is used, without overlapping nicegui?

Likely to be an issue with uvicorn (encode/uvicorn#1972).

**Comment by superlou** [comment]
> [@superlou](https://github.com/superlou) To remove NiceGUI from the equation, I like to use the following minimal FastAPI/Uvicorn example:
> ... 
> You can store this as main.py and run via `python3 main.py`.

That code has largely the same behavior, though for whatever reason, both nicegui and that fastapi snippet don't hang as badly as they seemed to when I first opened this issue. That said, the vanilla fastapi snippet still doesn't automatically refresh and appears frozen until I right-click on the terminal. That seems to confirm @sht2017 thought that this isn't a nicegui root cause.

**Comment by falkoschindler** [comment]
Thanks everyone for the investigation! Indeed it looks like a uvicorn issue which we can't do much about. It needs to be fixed upstream. Let's close this issue.

**Comment by Tooblippe** [comment]
[Windows] - We have gone very far in developing a very "Nice" application but, we made the regretable decision to abort our efforts on Nicegui. The constant disconnections and file watcher slow reloads have made the developer experience on Windows unfavourable. This was present from a very basic app with one button all the way up to a threaded engineering solver. I think the experience will be better on linux, as per this dicussion thread but unfortanately our application has to run on Windows. Will check back again from time to time to see if there are any improvements. Nicegui is my framework of choice as my mind works well with the paradigm and design philosopy of NiceGui. In our opinion its just not production ready on windows. But ill keep on using it for small projects. The plusses of having Quasar and Tailwind under the hood is unmathced in other frameworks, but the snappy reload times and solid out of the box flex elements of lets say Reflex might have to make up for the loss of these nice Nicegui attributes.  I  also just want to add that if we continued I was going to try and add documentation regarding State mangement This is in my humble opinion an area which could be improved in the documentation.

**Comment by platinops** [comment]
After years without any issues, I started having similar problems recently. NiceGUI would take a long time to reload, or spawn some subprocess/multiprocessing error out of nowhere.

I came across https://github.com/Kludex/uvicorn/issues/2000, which refers to https://github.com/Kludex/uvicorn/pull/2604.

That PR was in [0.34.2](https://github.com/Kludex/uvicorn/releases/tag/0.34.2), but I was on `0.34.0`. So I bumped `uvicorn` to the latest `0.46.0` (or even `0.34.2`) and the problem is gone. 

Anyone else with the same issue can confirm this?

If so, hope we can update the dependency in `nicegui` accordingly. Currently it's `uvicorn[standard]>=0.22.0`.
