### ISSUE TITLE
Runtime error in middleware behind a proxy

### ISSUE THREAD

**Issue by Lgtlebrun** [zauberzeug/nicegui#3851]
### Description

# Context
I want to integrate an existing FastAPI to niceGUI. The application runs behind a proxy configured with nginx. 
I also need a login prior to granting access to the application, so the authentification and Fastapi examples looked like a good start. However I am encountering persisting errors with the starlette handling of middleware.

 # Architecture 

The project is organized this way : 
project
|-Makefile
|-project
| |-\_\_init\_\_.py (empty)
| |-frontend.py
| |-main.py

In the makefile, I run the command : 
`uvicorn project.main:app --workers 1 --log-level info --host 0.0.0.0 --port 8080 --root-path /project`
as suggested [here](https://fastapi.tiangolo.com/advanced/behind-a-proxy/)

# main.py
The main file basically reproduces the fastapi examples, with the root_path specified for communication behind the proxy : 

```
#!/usr/bin/env python3
from . import frontend
from fastapi import FastAPI

app = FastAPI(root_path="/project")


@app.get('/api')
def read_root():
    return {'Hello': 'World'}


frontend.init(app)
if __name__ in {"__main__", "__mp_main__"}:

    print('Please start the app with the "uvicorn" command in the Makefile')

```

# frontend.py
The frontend mixes the authentification and fastapi examples :
```
from fastapi import FastAPI

from typing import Optional
from fastapi import Request
from fastapi.responses import RedirectResponse
from fastapi import HTTPException
from starlette.middleware.base import BaseHTTPMiddleware

from sqlalchemy import select

from nicegui import app, ui

passwords = {'user1': 'pass1', 'user2': 'pass2'}

mount_path='/project'  
unrestricted_page_routes = {mount_path + '/login'}

def init(fastapi_app: FastAPI) -> None:
    @ui.page('/')
    def main_page() -> None:
        def logout() -> None:
            app.storage.user.clear()
            ui.navigate.to('/login')

        with ui.column().classes('absolute-center items-center'):
            ui.label(f'Hello {app.storage.user["username"]}!').classes('text-2xl')
            ui.button(on_click=logout, icon='logout').props('outline round')

        

    @ui.page('/login')
    def login() -> Optional[RedirectResponse]:
        def try_login() -> None:  # local function to avoid passing username and password as arguments
            if passwords.get(username.value) == password.value:
                app.storage.user.update({'username': username.value, 'authenticated': True})
                ui.navigate.to(app.storage.user.get('referrer_path', '/'))  # go back to where the user wanted to go
            else:
                ui.notify('Wrong username or password', color='negative')

        if app.storage.user.get('authenticated', False):
            return RedirectResponse('/')
        with ui.card().classes('absolute-center'):
            username = ui.input('Username').on('keydown.enter', try_login)
            password = ui.input('Password', password=True, password_toggle_button=True).on('keydown.enter', try_login)
            ui.button('Log in', on_click=try_login)
        return None

    app.add_middleware(AuthMiddleware) # Adds the authentification middleware

    ui.run_with(
        fastapi_app,
        storage_secret='SECRET',  # NOTE setting a secret is optional but allows for persistent storage per user
    )


class AuthMiddleware(BaseHTTPMiddleware):
    """This middleware restricts access to all NiceGUI pages.

    It redirects the user to the login page if they are not authenticated.
    """

    async def dispatch(self, request: Request, call_next):
        if not app.storage.user.get('authenticated', False):
            # 
            if not request.url.path.startswith(mount_path+'/_nicegui') and request.url.path not in unrestricted_page_routes:
                app.storage.user['referrer_path'] = request.url.path  # remember where the user wanted to go
                return RedirectResponse('login')
        return await call_next(request)
```

Notice those critical changes : I had to add `mount_path` prefix to both unrestricted pages url and /_nicegui files url in `dispatch()`, so that the proxy resolves correctly both the app and the niceGUI static files without entering e.g. infinite redirection to /project/login, or 404 errors.

# The error

The website shows correctly. However no interactive feature (e.g. toggle or login button) work and this error message pops up on the server side in a loop : 

ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
  |     response_sent.set()
  |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    |     await self.app(scope, receive, send_wrapper)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     response_sent.set()
    |   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    |     self.gen.throw(type, value, traceback)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/nicegui/storage.py", line 86, in dispatch
    |     response = await call_next(request)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     response_sent.set()
    |   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    |     self.gen.throw(type, value, traceback)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/antenna/src/esoc2ui/esoc2ui/frontend.py", line 69, in dispatch
    |     return await call_next(request)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     response_sent.set()
    |   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    |     self.gen.throw(type, value, traceback)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/nicegui/middlewares.py", line 10, in dispatch
    |     response = await call_next(request)
    |   File "/home/antenna/src/sked/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 164, in call_next
    |     raise RuntimeError("No response returned.")
    | RuntimeError: No response returned.
    +------------------------------------

Sorry for the gigantic isue report, but this seemed to me more important than the scope of my only project. I hope I am simply doing something wrong! Best regards to the entire team.

**Comment by rodja** [comment]
NiceGUI also wants to establish a websocket connection. Maybe, through the `mount_path` the authentification is rejected. I suggest you look into the network traffic logs on the browser to find the right url...
