### ISSUE TITLE
Issue when running in native mode and the solution

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#3892]
### Description

I'm trying to run in native mode  - Sample code:
```py
from nicegui import ui
ui.label("hello world")
ui.run(native=True)
```
but I get the following error message:
```
[pywebview] WebView2 initialization failed with exception:
  (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()
```
A solution I've found is to import pywinauto.  So this works fine.
```py
from nicegui import ui
import pywinauto
ui.label("hello world")
ui.run(native=True)
```

I'm using nicegui 2.1.0.  I don't know if its just me (maybe I've imported a different version of a library somewhere?), but it might be a more general issue.

Thanks

Gavin

**Comment by gavinpotter** [comment]
Thanks - I tried running your webview code and it produced the s ame error, suggesting its a pywebview or environment error.

**Comment by gavinpotter** [comment]
Not a Nicegui issue
