### ISSUE TITLE
NiceGUI import fails (on clean Replit)

### ISSUE THREAD

**Issue by gloomie** [zauberzeug/nicegui#431]
Even Hello World example produces this on a clean Replit environment with only nicegui package installed:

`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import nicegui
  File "/home/runner/nice-bin/venv/lib/python3.10/site-packages/nicegui/__init__.py", line 1, in <module>
    from . import elements, globals, ui
  File "/home/runner/nice-bin/venv/lib/python3.10/site-packages/nicegui/ui.py", line 3, in <module>
    from .element import Element as element
  File "/home/runner/nice-bin/venv/lib/python3.10/site-packages/nicegui/element.py", line 9, in <module>
    from typing_extensions import Self
ImportError: cannot import name 'Self' from 'typing_extensions' (/home/runner/nice-bin/venv/lib/python3.10/site-packages/typing_extensions.py)`

**Comment by gloomie** [comment]
Installing nicegui from shell gives me this notification:
replit 3.2.5 requires typing_extensions<4.0.0,>=3.7.4, but you have typing-extensions 4.5.0 which is incompatible.

**Comment by gloomie** [comment]
I managed to get typing-extensions 4.5.0 but there is still a problem on output:
NiceGUI ready to go on http://0.0.0.0:8080
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/flutter_service_worker.js?v=672402291 not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/socket.io.min.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/fonts.css not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/quasar.prod.css not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/quasar.umd.prod.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/tailwind.min.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/vue.global.prod.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/socket.io.min.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/tailwind.min.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/fonts.css not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/quasar.prod.css not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/vue.global.prod.js not found
http://3a184e15-317e-490d-89aa-89a4d821224c.id.repl.co/_nicegui/static/quasar.umd.prod.js not found

**Comment by falkoschindler** [comment]
Thanks for reaching out, @gloomie!

Regarding typing-extensions: There seems to be an issue with replit depending on ^3.7.4 (excluding versions >=4.0.0):
https://ask.replit.com/t/replit-py-version-conflicts-typing-extensions-should-be-v4/3660
typing-extensions 4.0.0 has been released in 2021, so I think replit should update its dependency definition.
The whole point in NiceGUI depending on typing-extensions is to use most recent typing features that are not part of Python3.7 (the earliest Python version we officially support). If we would reduce the dependency to <4.0.0, we better wouldn't use it at all.

Regarding routing errors for static files: @rodja, do you have an idea what could be the problem?

**Comment by gloomie** [comment]
Regarding typing-extensions the solution I found to install 4.5 is here (for future readers):
https://ask.replit.com/t/what-is-that-i-dont-understand-this-error/10891/2

But I can't find anything for the missing files when running nicegui now...

**Comment by rodja** [comment]
The missing files problem looks very similar to #386. Please have a look at that issue and try out the suggestions.

**Comment by falkoschindler** [comment]
@gloomie I'll close this issue for now. If the problem persists, feel free to reopen it with additional information.

**Comment by Bullish-Design** [comment]
Hi, I'm getting the "flutter_service_worker" not found error, happening repeatedly whenever I interact with my app. It occurs every time I run a locally deployed NiceGUI app, so the terminal looks something like this:


NiceGUI ready to go on http://0.0.0.0:8080
http://127.0.0.1:8080/flutter_service_worker.js?v=672402291 not found
http://127.0.0.1:8080/flutter_service_worker.js?v=672402291 not found
http://127.0.0.1:8080/flutter_service_worker.js?v=672402291 not found
...

And carries on until I kill the app. All functionality seems to be okay, I just really want that error message to quit firing. 

Let me know if there's anything else I can help provide. Thanks!

**Comment by rodja** [comment]
@Bullish-Design this has nothing to do with NiceGUI imports or Replit. Please make sure you open a new discussion for unrelated questions next time. It looks like there is some other program requesting the flutter_service_worker.js file. Do you happen to have a mobile phone or simulator running?

**Comment by falkoschindler** [comment]
In https://github.com/zauberzeug/nicegui/discussions/539 we discussed similar problems and could make some progress.

1. `pip install --upgrade typing_extensions` fixes the problem with "cannot import name 'Self'".
2. For serving static files we need to add `follow_symlink=True`: [23a1173](https://github.com/zauberzeug/nicegui/commit/23a1173e0a6f2341a639157332b6b73ff7ba626e)

By solving the second problem, we finally _really_ solved this issue. Therefore I'll add this issue to the 1.2.4 milestone.
