### ISSUE TITLE
pyinstaller exe build give error on static folder

### ISSUE THREAD

**Issue by Asterix45** [zauberzeug/nicegui#619]
Just trying to redistribute a simple application with pyinstaller on windows, this is my code

main.py

```
from nicegui import ui

columns = [
    {'name': 'name', 'label': 'Name', 'field': 'name', 'required': True, 'align': 'left'},
    {'name': 'age', 'label': 'Age', 'field': 'age', 'sortable': True},
    {'name': 'html', 'label': 'html', 'field': 'html', 'sortable': False},
]
rows = [
    {'name': 'Alice', 'age': 18, 'html':'<input type="text"/>'},
    {'name': 'Bob', 'age': 21},
    {'name': 'Carol'},
]
ui.table(columns=columns, rows=rows, row_key='name')

ui.run()
```

and just start pyinstaller with

`pyinstaller --onefile main.py`

runnable file is correctly created but when started I have this error:
```
Traceback (most recent call last):
  File "test_nicegui.py", line 1, in <module>
    from nicegui import app, ui
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\ui.py", line 60, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\elements\upload.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\nicegui.py", line 32, in <module>
  File "starlette\staticfiles.py", line 57, in __init__
RuntimeError: Directory 'C:\Users\D50A7~1.VAS\AppData\Local\Temp\_MEI119122\nicegui\static' does not exist
[15508] Failed to execute script 'test_nicegui' due to unhandled exception!
```

I've modificed my script in this way to handle the static folder by code

```
from nicegui import app, ui
import os

if not os.path.exists('examples'):
    os.makedirs('examples')
app.add_static_files('/examples', 'examples')

...
```

folder `examples` is created on local debug but is not created with the executable and it gives the same error.

**Comment by rodja** [comment]
Have you looked at https://nicegui.io/reference#package_for_installation? I think you are missing `ui.run(reload=False)`.

**Comment by Asterix45** [comment]
Yes! With the example in the documentations works fine. I've tryed searching for **nicegui pyinstaller** on google but noting appears.
Thanks for the help!
