### ISSUE TITLE
Installation Error? 

### ISSUE THREAD

**Issue by Jesstr8803** [zauberzeug/nicegui#7]
Hello,

I'm fairly new to python, but I want to try and use NiceGUI. Unfortunately after i have installed the module with pip, I get an error that says ModuleNotFoundError: No module named 'nicegui'.

Thank you!

**Comment by rodja** [comment]
This can happen if you have multiple versions of python installed. Please try to install and run it like this:

```
python3 -m pip install nicegui
python3 -c 'from nicegui import ui; ui.label("it works"); ui.run(port=8080)'
```

**Comment by Jesstr8803** [comment]
@rodja,
Thanks for getting back to me, I think you are correct, I'm using Raspbian Bullseye. When I run the above commands, it seems like the nice gui module actually loads, but I do get a bunch of other errors after, 

```
 $ python3 -c 'from nicegui import ui; ui.label("it works"); ui.run(port=8080)'
Could not main script. Starting with interactive mode.
/home/pi/.local/lib/python3.7/site-packages/justpy
Module directory: /home/pi/.local/lib/python3.7/site-packages/justpy, Application directory: /home/pi
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/nicegui/__init__.py", line 1, in <module>
    from nicegui.nicegui import app, ui
  File "/home/pi/.local/lib/python3.7/site-packages/nicegui/nicegui.py", line 5, in <module>
    from .ui import Ui  # NOTE: before justpy
  File "/home/pi/.local/lib/python3.7/site-packages/nicegui/ui.py", line 1, in <module>
    class Ui:
  File "/home/pi/.local/lib/python3.7/site-packages/nicegui/ui.py", line 16, in Ui
    from .elements.log import Log as log
  File "/home/pi/.local/lib/python3.7/site-packages/nicegui/elements/log.py", line 9, in <module>
    class LogView(CustomView):
  File "/home/pi/.local/lib/python3.7/site-packages/nicegui/elements/log.py", line 11, in LogView
    def __init__(self, lines: deque[str], max_lines: int):
TypeError: 'type' object is not subscriptable
```

Is there anyway to remedy having python 3 and python 2? Do you perhaps know if it is safe to remove Python2 on the raspbian image?

**Comment by falkoschindler** [comment]
@Jesstr8803 Thanks for your feedback! There was an incompatibility with Python3.7, which should now be fixed with the latest NiceGUI release 0.7.0. Feel free to try it out and let us know if there are still problems.

Having Python2 and 3 installed is usually no problem. But if you installed packages via `pip install ...` you might have addressed the Python2 installation and Python3 still doesn't know the new package. That's why it is recommended to use Pip for Python3 explicitly via `python3 -m pip install ...`. Likewise, you should run your Python script with `python3 main.py` or with a shebang line like `#!/usr/bin/env python3` - always specifying the Python version 2 or 3.

**Comment by rodja** [comment]
@Jesstr8803 have you managed to start your script? Installing the latest version of NiceGUI can be done by running

```bash
python3 -m pip install -U nicegui
```

**Comment by Jesstr8803** [comment]
Sorry @rodja and @falkoschindler, I have not yet had time to test anything. I'll try to do it tonight. Thanks for all the help so far!

**Comment by Jesstr8803** [comment]
@rodja @falkoschindler, I finally had a chance to try this again. But I had to switch back to Buster (I should also mention I'm using a Pi0 2). I'm building a time-lapse camera with a web interface, and I guess the picamera functionality changed with the release of bullseye, and the python library hasn't been updated as of yet. While trying to install NiceGUI using `python3 -m pip install -v -U nicegui` everything seems to go good until it gets to compiling NumPy. which takes forever, eventually hangs, and my ssh session terminates and the pi become unresponsive. Currently I'm trying to see if I can just install NumPy first by itself. I'll report back when I got some new information.

**Comment by rodja** [comment]
@Jesstr8803 you can try using the Anaconda package manager. It should provide a precompiled NumPy for your Pi.
