### ISSUE TITLE
Live updating pyplot

### ISSUE THREAD

**Issue by nghia-vo** [zauberzeug/nicegui#780]
### Description

I want to have a live updating pyplot (matplotlib.pyplot) which can be a graph or image. There's an [example](https://nicegui.io/documentation/line_plot) for line plot but not for pyplot. I tried the following for pyplot but it didn't work. I guess we need to clear and redraw the plot content, but don't know how to do that in the nicegui framework.

```python
import numpy as np
from matplotlib import pyplot as plt
from nicegui import ui


def show_plot():
    with main_plot:
        pos = 1 + int(slice_pos.text)
        x = np.linspace(0.0, pos)
        y = np.cos(2 * np.pi * x) * np.exp(-x)
        plt.plot(x, y, '-')
main_plot = ui.pyplot(figsize=(8, 5))
main_slider = ui.slider(min=0, max=19, value=0, on_change=lambda: show_plot())
slice_pos = ui.label()
slice_pos.bind_text_from(main_slider, 'value')
ui.run()
``` 
which returns the following error:
```console
can't delete Tcl command
Traceback (most recent call last):
  File "C:\Users\nv\miniconda3\envs\webview\lib\site-packages\nicegui\events.py", line 281, in handle_event
    result = handler() if no_arguments else handler(arguments)
  File "C:\Users\nv\PycharmProjects\webview\main.py", line 15, in <lambda>
    main_slider = ui.slider(min=0, max=19, value=0, on_change=lambda: show_plot())
  File "C:\Users\nv\PycharmProjects\webview\main.py", line 11, in show_plot
    plt.plot(x, y, '-')
  File "C:\Users\nv\miniconda3\envs\webview\lib\site-packages\nicegui\elements\pyplot.py", line 40, in __exit__
    plt.close(self.fig)
  File "C:\Users\nv\miniconda3\envs\webview\lib\site-packages\matplotlib\pyplot.py", line 925, in close
    _pylab_helpers.Gcf.destroy_fig(fig)
  File "C:\Users\nv\miniconda3\envs\webview\lib\site-packages\matplotlib\_pylab_helpers.py", line 75, in destroy_fig
    cls.destroy(num)
  File "C:\Users\nv\miniconda3\envs\webview\lib\site-packages\matplotlib\_pylab_helpers.py", line 66, in destroy
    manager.destroy()
  File "C:\Users\nv\miniconda3\envs\webview\lib\site-packages\matplotlib\backends\_backend_tk.py", line 529, in destroy
    self._window_dpi.trace_remove('write', self._window_dpi_cbname)
  File "C:\Users\nv\miniconda3\envs\webview\lib\tkinter\__init__.py", line 430, in trace_remove
    self._tk.deletecommand(cbname)
```

**Comment by falkoschindler** [comment]
Hi @nghia-vo!
You're code works for me. But maybe you need to explicitly keep the plot open:
```py
main_plot = ui.pyplot(figsize=(8, 5), close=False)
```
Does that help?

**Comment by falkoschindler** [comment]
By the way: You can use `plt.clf()` to clear the plot before drawing a new line.

**Comment by nghia-vo** [comment]
The option close=False works. Thanks very much. It would be fantastic if nicegui has API documentation with docstrings like Numpy reference.

**Comment by falkoschindler** [comment]
Of course, there is always room for improvement. But this parameter is covered here:
https://github.com/zauberzeug/nicegui/blob/c558d1e29d0f08dea79b60a50534b67545d0752b/nicegui/elements/pyplot.py#L17
