### ISSUE TITLE
Sessions example has ModuleNotFoundError in it

### ISSUE THREAD

**Issue by frankhuurman** [zauberzeug/nicegui#961]
### Description

When I tested my NiceGUI application on my phone I noticed that the application on my desktop responded to input at the same time which made me want to look into sessions so every connected client has its own session.

I've made a new empty Python file and copied the example from https://nicegui.io/documentation#sessions in it, ran it, and bumped into the following error:
```
Traceback (most recent call last):
  File "C:\Users\myuser\Documents\nicegui\app.py", line 5, in <module>
    from starlette.middleware.sessions import SessionMiddleware
  File "C:\Users\myuser\Documents\nicegui\venv\lib\site-packages\starlette\middleware\sessions.py", line 6, in <module>
    import itsdangerous
ModuleNotFoundError: No module named 'itsdangerous'
```

I'm using Windows 10, Python 3.10.4 and NiceGUI version 1.2.14.

_Would be great if we could get built-in support voor sessions(like Streamlit has by default) as an argument to ui.run().
Also removes the need for extra uuid/starlette imports like with this Sessions example 😄_

**Comment by rodja** [comment]
Try installing the package `itsdangerous`. This is not in the NiceGUI dependencies because it is not (yet) strictly required. This will change when we make the session more accessible as you suggested and has it's ongoing discussion in #732.

**Comment by frankhuurman** [comment]
That fixes it indeed 😄 

Thanks for the suggestion. I'll follow the ongoing discussion for session management!
